### ISSUE TITLE
Random disconnection

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#106]
Not sure if you have an idea of what caused this:

hotstamp left the game voluntarily.  Minecraftboy was kicked afterwards.
```
[18:58:38] [Server thread/INFO]: hotstamp[/127.0.0.1:58825] logged in with entit
y id 21391 at (235.9104957303117, 6.0, -60.79034256214702)
[18:58:38] [Server thread/INFO]: hotstamp joined the game
[18:59:19] [Wrapper.py/INFO] Minecraftboy2019 executed: /tp Minecraftboy2019 hot
stamp
[18:59:19] [Server thread/INFO]: [Minecraftboy2019: Teleported Minecraftboy2019
to hotstamp]
[18:59:25] [Wrapper.py/INFO] Minecraftboy2019 executed: /gamemode 3
[18:59:25] [Server thread/INFO]: [Minecraftboy2019: Set own game mode to Spectat
or Mode]
[18:59:53] [Wrapper.py/INFO] Minecraftboy2019 executed: /gamemode 3 hotstamp
[18:59:53] [Server thread/INFO]: [Minecraftboy2019: Set hotstamp's game mode to
Spectator Mode]
[19:00:40] [Wrapper.py/INFO] Minecraftboy2019 executed: /gamemode 1 hotstamp
[19:00:40] [Server thread/INFO]: [Minecraftboy2019: Set hotstamp's game mode to
Creative Mode]
Last packet IDs (Server->Client) before disconnection:
[('0x1a', 6), ('0x12', 10), ('0x17', 10), ('0x19', 5), ('0x15', 8), ('0x17', 10)
, ('0x19', 5), ('0x15', 8), ('0x17', 10), ('0x19', 5)]
Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "src\proxy.py", line 761, in handle
    id, original = self.packet.grabPacket()
  File "src\proxy.py", line 821, in grabPacket
    dataLength = self.unpack_varInt()
  File "src\proxy.py", line 845, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "src\proxy.py", line 1003, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

Last packet IDs (Server->Client) before disconnection:
[('0x1a', 6), ('0x12', 10), ('0x17', 10), ('0x19', 5), ('0x15', 8), ('0x17', 10)
, ('0x19', 5), ('0x15', 8), ('0x17', 10), ('0x19', 5)]
[19:00:57] [Wrapper.py/DEBUG] Could not parse packet, connection may crumble:
[19:00:57] [Wrapper.py/DEBUG] Traceback (most recent call last):
[19:00:57] [Wrapper.py/DEBUG]   File "src\proxy.py", line 781, in handle
[19:00:57] [Wrapper.py/DEBUG]     if self.parse(id, original) and self.safe:
[19:00:57] [Wrapper.py/DEBUG]   File "src\proxy.py", line 718, in parse
[19:00:57] [Wrapper.py/DEBUG]     client = self.client.proxy.getClientByServerUU
ID(serverUUID)
[19:00:57] [Wrapper.py/DEBUG]   File "src\proxy.py", line 87, in getClientByServ
erUUID
[19:00:57] [Wrapper.py/DEBUG]     return uuid.UUID(hex=self.uuidTranslate[str(id
)])
[19:00:57] [Wrapper.py/DEBUG]   File "C:\Python27\lib\uuid.py", line 134, in __i
nit__
[19:00:57] [Wrapper.py/DEBUG]     raise ValueError('badly formed hexadecimal UUI
D string')
[19:00:57] [Wrapper.py/DEBUG] ValueError: badly formed hexadecimal UUID string
[19:00:57] [Wrapper.py/DEBUG]
[19:00:57] [Server thread/INFO]: hotstamp lost connection: TranslatableComponent
{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException:
An existing connection was forcibly closed by the remote host], siblings=[], sty
le=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, o
bfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[19:00:57] [Server thread/INFO]: hotstamp left the game
Traceback (most recent call last):
  File "src\proxy.py", line 761, in handle
    id, original = self.packet.grabPacket()
  File "src\proxy.py", line 815, in grabPacket
    length = self.unpack_varInt()
  File "src\proxy.py", line 845, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "src\proxy.py", line 1005, in recv
    raise EOFError("Packet was zero length, disconnecting")
EOFError: Packet was zero length, disconnecting

Last packet IDs (Server->Client) before disconnection:
[('0x15', 8), ('0x15', 8), ('0x17', 10), ('0x19', 5), ('0x1a', 6), ('0x17', 10),
 ('0x19', 5), ('0x12', 10), ('0x19', 5), ('0x0', 6)]
[19:01:05] [Server thread/INFO]: Minecraftboy2019 lost connection: TranslatableC
omponent{key='disconnect.genericReason', args=[Internal Exception: io.netty.hand
ler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9)
+ length(8) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 9, widx: 10, cap:
 10)], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=n
ull, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, inserti
on=null}}
[19:01:05] [Server thread/INFO]: Minecraftboy2019 left the game
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "src\proxy.py", line 464, in handle
    id, original = self.packet.grabPacket()
  File "src\proxy.py", line 821, in grabPacket
    dataLength = self.unpack_varInt()
  File "src\proxy.py", line 845, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "src\proxy.py", line 1003, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

**Comment by saltstorm** [comment]
I've had this exact issue. It must be a bug in the newer versions?

**Comment by suresttexas00** [comment]
I think it's always been there

**Comment by saltstorm** [comment]
This is the pretty big issue and I hope it gets fixed soon.

**Comment by saltstorm** [comment]
After further investigation I think I have found the cause for this error.

The version before this line was added work fine. https://github.com/benbaptist/minecraft-wrapper/blob/master/src/server.py#L192

**Comment by suresttexas00** [comment]
I tried commenting out that line and setting the argument to False.  Does not seem to make a difference.

**Comment by suresttexas00** [comment]
I think this is causing many of my players to leave.

**Comment by suresttexas00** [comment]
I think it is fixed.. i have not observed any issues now.
