### ISSUE TITLE
Error __file__ - have no idea what prompted it.

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#125]
```
[14:13:06] [Wrapper.py/ERROR] Plugin 'Server' errored out when executing callbac
k event 'timer.second':
[14:13:06] [Wrapper.py/ERROR] Traceback (most recent call last):
[14:13:06] [Wrapper.py/ERROR]   File "C:\Users\JRUSSELL\Desktop\vanilla\src\__ma
in__.py", line 139, in callEvent
[14:13:06] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[14:13:06] [Wrapper.py/ERROR]   File "src\server.py", line 444, in onTick
[14:13:06] [Wrapper.py/ERROR]     size += os.path.getsize(os.path.join(i[0], f))

[14:13:06] [Wrapper.py/ERROR]   File "C:\Python27\lib\genericpath.py", line 49,
in getsize
[14:13:06] [Wrapper.py/ERROR]     return os.stat(filename).st_size
[14:13:06] [Wrapper.py/ERROR] WindowsError: [Error 2] The system cannot find the
 file specified: 'AllTheWorld\\playerdata\\5511d45b-bd3a-3c15-8616-59e6ebcd8663.
dat'
[14:13:06] [Wrapper.py/ERROR]
```

**Comment by suresttexas00** [comment]
I'll try to gather more info... this happened while I was away just writing plugin code.

**Comment by suresttexas00** [comment]
I have nothing further to add.. spurious error with no additional info
