### ISSUE TITLE
Got hammered!

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#129]
after getting about 6-10 players on at once, somewhere along the way, my plugins hiccuped and "I" could not get any farther than "downloading terrain" when I logged on.. here is the console at the time:

Maybe related to Tom's #124  issue
```
Wrapper\__main__.py", line 139, in callEvent
[15:26:48] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:26:48] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:26:48] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:26:48] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:26:48] [Wrapper.py/ERROR]
[15:26:48] [Server thread/INFO]: <lightningswrath> you framer
[15:26:48] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:26:48] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:26:48] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:26:48] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:26:48] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:26:48] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:26:48] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:26:48] [Wrapper.py/ERROR]
[15:26:51] [Server thread/INFO]: <Hawksrock250> sorry
[15:26:58] [Server thread/INFO]: <Hawksrock250> just stating the facts
[15:27:07] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.global' errored
out when executing callback event 'player.rawMessage':
[15:27:07] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:27:07] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:27:07] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:27:07] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:27:07] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:27:07] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:27:07] [Wrapper.py/ERROR]
[15:27:07] [Server thread/INFO]: <lightningswrath> cough cough opinions
[15:27:07] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:27:07] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:27:07] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:27:07] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:27:07] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:27:07] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:27:07] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:27:07] [Wrapper.py/ERROR]
[15:27:20] [Wrapper.py/WARN] [184.17.171.192] Executed: /tell superknight106 im
stuck at downloading terrain
[15:27:21] [Server thread/INFO]: You whisper to SuperKnight106: im stuck at down
loading terrain
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 468, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 819, in grabPacket
    length = self.unpack_varInt()
  File "Wrapper\proxy.py", line 849, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1007, in recv
    d = self.socket.recv(length)
error: [Errno 10054] An existing connection was forcibly closed by the remote ho
st

Last packet IDs (Server->Client) before disconnection:
[('0x37', 52), ('0x3e', 64), ('0x3e', 45), ('0x3e', 45), ('0x3e', 103), ('0x3e',
 49), ('0x38', 37), ('0x38', 38), ('0x38', 36), ('0x38', 39)]
[15:27:26] [Server thread/INFO]: SurestTexas00 lost connection: TextComponent{te
xt='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=nu
ll, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=n
ull, insertion=null}}
[15:27:26] [Server thread/INFO]: SurestTexas00 left the game
[15:27:33] [Server thread/INFO]: <Hawksrock250> cough cough my entire inventory
is gone cough cough'
[15:27:36] [Wrapper.py/INFO] SuperKnight106 executed: /msg server That sucks
[15:27:41] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.global' errored
out when executing callback event 'player.rawMessage':
[15:27:41] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:27:41] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:27:41] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:27:41] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:27:41] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:27:41] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:27:41] [Wrapper.py/ERROR]
[15:27:41] [Server thread/INFO]: <lightningswrath> SAME HERE for your insolence
[15:27:41] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:27:41] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:27:41] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:27:41] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:27:41] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:27:41] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:27:41] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:27:41] [Wrapper.py/ERROR]
[15:27:41] [Server thread/INFO]: <Hawksrock250> gough gough lightning cough coug
h
[15:27:58] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.global' errored
out when executing callback event 'player.rawMessage':
[15:27:58] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:27:58] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:27:58] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:27:58] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:27:58] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:27:58] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:27:58] [Wrapper.py/ERROR]
[15:27:58] [Server thread/INFO]: <lightningswrath> and if its been taked care of
 WHY DONT I HAVE A BUCKET OF MILK
[15:27:58] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:27:58] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:27:58] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:27:58] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:27:58] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:27:58] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:27:58] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:27:58] [Wrapper.py/ERROR]
[15:28:10] [Server thread/INFO]: <Hawksrock250> because you deserve it
[15:28:11] [Server thread/INFO]: <SuperKnight106> lightningswrath calm down.
[15:28:19] [Server thread/INFO]: <Hawksrock250> all my stuff, murdering me
[15:28:21] [Server thread/INFO]: <SuperKnight106> A milk bucket won't fix it
[15:28:29] [Server thread/INFO]: <SuperKnight106> I can't use /restore on you
[15:28:30] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.global' errored
out when executing callback event 'player.rawMessage':
[15:28:30] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:28:30] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:28:30] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:28:30] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:28:30] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:28:30] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:28:30] [Wrapper.py/ERROR]
[15:28:30] [Server thread/INFO]: <lightningswrath> i murdered you because you we
re trying to murder me
[15:28:30] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:28:30] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:28:30] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:28:30] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:28:30] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:28:30] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:28:30] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:28:30] [Wrapper.py/ERROR]
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 468, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 819, in grabPacket
    length = self.unpack_varInt()
  File "Wrapper\proxy.py", line 849, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1007, in recv
    d = self.socket.recv(length)
error: [Errno 10054] An existing connection was forcibly closed by the remote ho
st

Last packet IDs (Server->Client) before disconnection:
[('0x37', 2), ('0x3e', 64), ('0x3e', 45), ('0x3e', 45), ('0x3e', 103), ('0x3e',
49), ('0x38', 35), ('0x38', 38), ('0x38', 36), ('0x38', 39)]
[15:28:32] [Server thread/INFO]: GeoRamp0734 lost connection: TranslatableCompon
ent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOExceptio
n: An existing connection was forcibly closed by the remote host], siblings=[],
style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null
, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[15:28:32] [Server thread/INFO]: GeoRamp0734 left the game
[15:28:47] [Server thread/INFO]: <Hawksrock250> ehhh no. because i was trying to
 stop my stealing
[15:28:47] [Wrapper.py/INFO] SuperKnight106 executed: /tpto AwesomeStormer27
[15:28:47] [Server thread/INFO]: Teleported SuperKnight106 to AwesomeStormer27
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 788, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 637, in parse
    self.proxy.getClientByServerUUID(data["uuid"]).uuid,
AttributeError: 'UUID' object has no attribute 'uuid'

[15:28:53] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.global' errored
out when executing callback event 'player.rawMessage':
[15:28:53] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:28:53] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:28:53] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:28:53] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:28:53] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:28:53] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:28:53] [Wrapper.py/ERROR]
[15:28:53] [Server thread/INFO]: <lightningswrath> i didnt steal anything
[15:28:53] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:28:53] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:28:53] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:28:53] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:28:53] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:28:53] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:28:53] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:28:53] [Wrapper.py/ERROR]
[15:29:06] [Server thread/INFO]: <Hawksrock250> ecept for 100% of my stuff
[15:29:11] [Wrapper.py/INFO] SuperKnight106 executed: /tpto cheeseandcracker
[15:29:11] [Server thread/INFO]: Teleported SuperKnight106 to cheeseandcracker
[15:29:17] [Server thread/INFO]: <SuperKnight106> lag
Last packet IDs (Server->Client) before disconnection:
[('0x33', 47), ('0x33', 42), ('0x33', 40), ('0xc', 76), ('0x1c', 44), ('0x20', 6
6), ('0x4', 12), ('0x1d', 8), ('0x1d', 8), ('0xc', 76)]
[15:29:20] [Server thread/INFO]: SuperKnight106 lost connection: TranslatableCom
ponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOExcep
tion: An existing connection was forcibly closed by the remote host], siblings=[
], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=n
ull, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[15:29:20] [Server thread/INFO]: SuperKnight106 left the game
[15:29:26] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.global' errored
out when executing callback event 'player.rawMessage':
[15:29:26] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:29:26] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:29:26] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:29:26] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:29:26] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:29:26] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:29:26] [Wrapper.py/ERROR]
[15:29:26] [Server thread/INFO]: <lightningswrath> -.- i saw u breaking chest so
 i avioded colecting stuff THATS WHY I RAN
[15:29:26] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:29:26] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:29:26] [Wrapper.py/ERROR]   File "C:\Users\Surest\Desktop\MInecraft\vanilla\
Wrapper\__main__.py", line 139, in callEvent
[15:29:26] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:29:26] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:29:26] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:29:26] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:29:26] [Wrapper.py/ERROR]
[15:29:27] [Wrapper.py/INFO] SuperKnight106 logged in (UUID: bf5542f5-dd14-477e-
a206-7af68b835c7f | IP: 72.23.241.88)
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 788, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 734, in parse
    properties = client.properties
AttributeError: 'UUID' object has no attribute 'properties'

[15:29:27] [Server thread/INFO]: SuperKnight106[/127.0.0.1:57565] logged in with
 entity id 369407 at (3259.5, 104.0, 2669.5)
[15:29:27] [Server thread/INFO]: SuperKnight106 joined the game
``

**Comment by suresttexas00** [comment]
This looks like a problem:

```
[15:27:41] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 39, in pl
ayerRawMessage
[15:27:41] [Wrapper.py/ERROR]     hisuuid = str(player.uuid)
[15:27:41] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'uu
id'
[15:27:41] [Wrapper.py/ERROR]
```

there are no Booleans in either argument.. that i'm aware of?

**Comment by suresttexas00** [comment]
I had to /restart to regain control and login

**Comment by benbaptist** [comment]
hmm, so the wrapper didn't need a restart - just the server? that's curious. it's like the server goes into some state/mode/something that the wrapper doesn't like. or maybe this is actually just a server bug and it's not showing an error message because wrapper sometimes has issues with showing kick messages? I dunno.

**Comment by benbaptist** [comment]
The error on the post looked to be referring to the player object - for
some reason, it is a Boolean instead of the player object.

**Comment by suresttexas00** [comment]
yep

**Comment by saltstorm** [comment]
Yep this is a similar thing to what happened to me. I'm no using the Web module mind you though.

**Comment by suresttexas00** [comment]
I figured it might have been the case.  I'm not ruing that my plugins might have exacerbated the situation because they need a little more error checking in places.  

from what i see of the errors, I think it might be that the plugins or wrapper itself might need to have beefier error checking.

In this case the web mode did allow me to stay in contact with my mod so he knew  what was going on.

**Comment by benbaptist** [comment]
Is this still happening? I've added a lot of changes since, and installed a lot more error-handling into the Wrapper than when this was originally posted. Is it safe to close yet?

**Comment by suresttexas00** [comment]
I have not had the opportunity to test this again with a nice load of players.  I'm still trying to improve and make my plugins more robust too.

**Comment by suresttexas00** [comment]
Shortly after the update to 1.8.3, I did get a nice load of players and did not experience any problems.
