### ISSUE TITLE
Web mode: public-stats interferes with Admin opetation

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#130]
benbaptist edit: public-stats causes issues with regular web mode operation.

The web interface stopped displaying content/feedback from the server wrapper.  I can still execute the functions (reload plugins, stop/start server, etc.  However, all the tabs lack any information.  I restarted the wrapper numerous times, but no luck:
![image](https://cloud.githubusercontent.com/assets/10001762/6118372/e5eb169c-b08a-11e4-8601-d4108bab2917.png)

**Comment by benbaptist** [comment]
What browser? Any errors in your browser's developer console/Javascript console, if any? Does the wrapper have any console errors? Was this after an update, or did anything else particularly happen as well when this began?

**Comment by suresttexas00** [comment]
CHrome.. there are no errors ANYWHERE... baffled.  Just came home after work.. decided to check in on the server.. and .. almost had a heart attack because I assumed my IP had changed..  But everything was OK and I connected with my client.

**Comment by suresttexas00** [comment]
On the server tab, I can load server.properties and I can also see "files" content... Chat and Console are blank.  Plugins tab is empty and dashboard tab is as above (dahsboard power button works).  about tab works, including Halt wrapper.

**Comment by benbaptist** [comment]
This is really confusing. I don't understand how it just broke out of nowhere. Are you on the latest build? I better make sure I didn't break the whole build or something.

**Comment by suresttexas00** [comment]
NO- there were no build changes or anything.. just poof!  I'm on the latest dev build.. have been since it came out.

**Comment by benbaptist** [comment]
BTW, is this still happening? I really don't understand what could've broken the web mode for you.

**Comment by suresttexas00** [comment]
I'm not sure either.  maybe there is some random character or setting that is glitching it out.  I'll let you know if it clears up or I find the cause

**Comment by suresttexas00** [comment]
I won't know if the latest updates fix this until I move them to the production server.  I have to make sure all the bugs worked out and plugins work with the new version first.

**Comment by suresttexas00** [comment]
This is my bad.. I did not know what this line, did so I set it to false at some point:
`public-stats = True`

**Comment by benbaptist** [comment]
I figure this bug isn't truly fixed,asthat behaviour is not intended. I will fix this.

**Comment by suresttexas00** [comment]
Well, it turns out, I still have issues anyway.  The basic stats (server MOTD, memory, Ram, etc) work now, and I can "send" chats and Commands, but:
1) The plugins page "comes and goes" as it pleases and reloading the plugins does not have 
2) The server power button does not work
3) The console and Chat windows are still blank (although they do "transmit" data - chats/commands successfully.
4) The player list is blank, as is the chat list.

**Comment by suresttexas00** [comment]
I am not sure if you knew this already or what, but even when it was working, only the last logged in player's shin could be seen in the player list...  Either I thought it was minor or I thought it was a known bug; I don't recall.

**Comment by benbaptist** [comment]
Any errors in your Javascript console now?

**Comment by suresttexas00** [comment]
No Java console errors since the last update.

**Comment by benbaptist** [comment]
I'm not talking about Java - I'm referring to JavaScript in the browser. On chrome, the JavaScript console for checking errors can easily be accessed by right clicking anywhere on the webpage, and hitting Inspect Element.

**Comment by suresttexas00** [comment]
Oh.. I thought you were referring to the console errors earlier.  I'll have to check on this...

**Comment by suresttexas00** [comment]
Everything with webmode seems fine in last release, even if It's just little ol me on the web! :)

**Comment by suresttexas00** [comment]
Well, its not working again:

I get onto the page, but then I get the "Connection lost - Make sure Wrapper.py is running..." 

refreshing the page over and over gives this console output:
```
Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte

[18:54:53] [Wrapper.py/WARN] 184.17.171.192 logged in to web mode (remember me:
False)
Traceback (most recent call last):
  File "Wrapper\web.py", line 473, in get
    self.write(json.dumps(self.handleAction(request)))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 33: invalid
start byte
``

**Comment by benbaptist** [comment]
Damn!

**Comment by suresttexas00** [comment]
yea, I know.  I thought this was licked.

**Comment by suresttexas00** [comment]
I am closing this too.. it might have been caused by oversize chats
