### ISSUE TITLE
Proxy problems

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#139]
Error 1 - occurs when server is pinged:
```
[12:37:34] [Wrapper.py/INFO] Server started
Error in the Client->Server method:
Traceback (most recent call last):
  File "src\proxy.py", line 510, in handle
    if self.parse(id) and self.server:
  File "src\proxy.py", line 308, in parse
    if self.serverIcon:
AttributeError: Client instance has no attribute 'serverIcon'
```

```
Find all "serverIcon", Find Results 1, Current Document
  C:\Users\JRUSSELL\Desktop\vanilla\src\proxy.py(25):		self.serverIcon = None
  C:\Users\JRUSSELL\Desktop\vanilla\src\proxy.py(39):			self.serverIcon = "data:image/png;base64," + f.read().encode("base64")
  C:\Users\JRUSSELL\Desktop\vanilla\src\proxy.py(308):				if self.serverIcon:
  C:\Users\JRUSSELL\Desktop\vanilla\src\proxy.py(309):					MOTD["favicon"] = self.serverIcon
Matching lines: 4
```

Error2 occurs during gameplay with various symptoms.. unable to load new chunks, inability to kill animals, etc:

```
[12:37:44] [Wrapper.py/INFO] tinking68 logged in (UUID: 5344845a-fb5e-4a7d-871b-
be682e27e29c | IP: 184.17.171.192)
[12:37:44] [Server thread/INFO]: tinking68[/127.0.0.1:54581] logged in with enti
ty id 7 at (-1828.9228180771374, 64.0, 7209.203999271342)
[12:37:44] [Server thread/INFO]: tinking68 joined the game
Error in the Server->Client method:
Traceback (most recent call last):
  File "src\proxy.py", line 818, in handle
    if self.parse(id, original) and self.safe:
  File "src\proxy.py", line 698, in parse
    player = self.getPlayerByEID(eid)
  File "src\proxy.py", line 577, in getPlayerByEID
    if client.server.eid == eid: return self.getPlayerContext(client.username)
AttributeError: 'NoneType' object has no attribute 'eid'
```

**Comment by benbaptist** [comment]
Should be fixed in the latest build once I push it.

**Comment by benbaptist** [comment]
Should be safe now. Try it out!
