### ISSUE TITLE
Chat item disconnects me

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#151]
When i say the following in chat:

`aw this is a nice ckicken farm setup.. think i saw that on utube.  I like the ones that auto kill`

I get disconnected.  Now, this MAY be a problem with my chat filtering plugin.  I have not looked into it yet.  I am only including it here first without investigating first because I noticed the error was traced through.in the web.py...

Console:
```
[15:18:11] [Server thread/INFO]: º9SurestTexas00ºr joined the game
[15:18:30] [Wrapper.py/INFO] SurestTexas00 executed: /tell AwesomeStormer27 did
you get those three messasges before i disconneted?
[15:18:53] [Wrapper.py/INFO] AwesomeStormer27 executed: /tell SurestTexas00 no i
 didnt
[15:18:56] [Wrapper.py/INFO] SurestTexas00 executed: /tell AwesomeStormer27 ok
[15:19:09] [Wrapper.py/INFO] AwesomeStormer27 executed: /tell SurestTexas00 it j
ust said SurestTexas00 left teh game
[15:19:33] [Wrapper.py/INFO] SurestTexas00 executed: /tell AwesomeStormer27 i ke
pt saying AwesomeStormer27 this is a nice ckicken farm setup.. think i saw that
on utube.  I like the
[15:19:53] [Wrapper.py/INFO] SurestTexas00 executed: /tell AwesomeStormer27 Awes
omeStormer27 this is a nice ckicken farm setup.. think i saw that on utube.  I l
ike the ones that aut
[15:20:02] [Wrapper.py/INFO] AwesomeStormer27 executed: /tell SurestTexas00 oh t
y
[15:20:03] [Wrapper.py/INFO] SurestTexas00 executed: /tell AwesomeStormer27 this
 is a nice ckicken farm setup.. think i saw that on utube.  I like the ones that
 auto k
[15:20:18] [Wrapper.py/INFO] AwesomeStormer27 executed: /tpto SurestTexas00
[15:20:18] [Server thread/INFO]: Teleported AwesomeStormer27 to SurestTexas00
[15:20:21] [Server thread/INFO]: <º9SurestTexas00ºr> if i chat it, it disconnect
s
[15:20:21] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:20:21] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:20:21] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:20:21] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:20:21] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:20:21] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:20:21] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:20:21] [Wrapper.py/ERROR]
[15:20:25] [Server thread/INFO]: <º9AwesomeStormer27ºr> oh
[15:20:26] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:20:26] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:20:26] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:20:26] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:20:26] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:20:26] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:20:26] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:20:26] [Wrapper.py/ERROR]
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 841, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 891, in grabPacket
    length = self.unpack_varInt()
  File "Wrapper\proxy.py", line 921, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1081, in recv
    raise EOFError("Packet was zero length, disconnecting")
EOFError: Packet was zero length, disconnecting

Last packet IDs (Server->Client) before disconnection:
[('0x15', 8), ('0x12', 10), ('0x12', 10), ('0x15', 8), ('0x12', 10), ('0x12', 10
), ('0x15', 8), ('0x2f', 6), ('0x2f', 6), ('0x2f', 6)]
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 530, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 897, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 921, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1079, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[15:20:27] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComp
onent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler
.codec.DecoderException: The received string length is longer than maximum allow
ed (111 > 100)], siblings=[], style=Style{hasParent=false, color=null, bold=null
, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=nul
l, insertion=null}}
{'player': <api.player.Player instance at 0x073BD620>}
[15:20:27] [Server thread/INFO]: º9SurestTexas00ºr left the game
[15:20:32] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a
612-fb4230588eff | IP: 184.17.171.192)
[15:20:32] [Server thread/INFO]: SurestTexas00[/127.0.0.1:57313] logged in with
entity id 54792 at (1013.58968356, 72.0, 716.026035591)
{'player': <api.player.Player instance at 0x032CA9B8>}
[15:20:32] [Server thread/INFO]: º9SurestTexas00ºr joined the game
[15:20:42] [Server thread/INFO]: <º9AwesomeStormer27ºr> hmmm
[15:20:42] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:20:42] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:20:42] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:20:42] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:20:42] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:20:42] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:20:42] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:20:42] [Wrapper.py/ERROR]
[15:20:43] [Server thread/INFO]: <º9SurestTexas00ºr> .aw this is a nice ckicken
farm setup.. think i saw that on utube. I like the ones that auto kill
[15:20:43] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:20:43] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:20:43] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:20:43] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:20:43] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:20:43] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:20:43] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:20:43] [Wrapper.py/ERROR]
[15:20:53] [Server thread/INFO]: <º9SurestTexas00ºr> its the auto-replace i thin
k
[15:20:53] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:20:53] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:20:53] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:20:53] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:20:53] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:20:53] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:20:53] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:20:53] [Wrapper.py/ERROR]
[15:20:58] [Server thread/INFO]: <º9AwesomeStormer27ºr> oh
[15:20:58] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:20:58] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:20:58] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:20:58] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:20:58] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:20:58] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:20:58] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:20:58] [Wrapper.py/ERROR]
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 841, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 891, in grabPacket
    length = self.unpack_varInt()
  File "Wrapper\proxy.py", line 921, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1081, in recv
    raise EOFError("Packet was zero length, disconnecting")
EOFError: Packet was zero length, disconnecting

Last packet IDs (Server->Client) before disconnection:
[('0x15', 8), ('0x19', 5), ('0x12', 10), ('0x15', 8), ('0x19', 5), ('0x12', 10),
 ('0x12', 10), ('0x15', 8), ('0x3', 17), ('0x24', 13)]
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 530, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 897, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 921, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1079, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[15:21:06] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComp
onent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler
.codec.DecoderException: The received string length is longer than maximum allow
ed (106 > 100)], siblings=[], style=Style{hasParent=false, color=null, bold=null
, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=nul
l, insertion=null}}
{'player': <api.player.Player instance at 0x032CA9B8>}
[15:21:06] [Server thread/INFO]: º9SurestTexas00ºr left the game
```

**Comment by suresttexas00** [comment]
A cursory review makes me think this is not related to my plugin.

**Comment by suresttexas00** [comment]
Found it!

The problem is the message length.  This message goes through:
`aw is a nice ckicken farm setup.. think i saw that on utube.  I like the ones that aut`
and is translated into 
`AwesomeStormer27 is a nice ckicken farm setup.. think i saw that on utube.  I like the ones that aut`

add a single character, and i get disconnected.

my plugin (due to the /alias which allows text substitutions like we discussed before; i.e op - benbaptist) allows for chat messages a bit larger than the code expects...

**Comment by suresttexas00** [comment]
There is something more to this. Even if I don't get disconnected, there are some web.py errors from chat:
```
[15:39:33] [Server thread/INFO]: <º9SurestTexas00ºr> ok.. gotta be careful with
your message lengths... our /alias allows them to be a little to large
[15:39:33] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:39:33] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:39:33] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:39:33] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:39:33] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:39:33] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:39:33] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:39:33] [Wrapper.py/ERROR]
[15:39:37] [Server thread/INFO]: <º9SurestTexas00ºr> ..sometimes
[15:39:37] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:39:37] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:39:37] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:39:37] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:39:37] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:39:37] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:39:37] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:39:37] [Wrapper.py/ERROR]
[15:39:42] [Server thread/INFO]: <º9AwesomeStormer27ºr> ok
[15:39:42] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:39:42] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:39:42] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:39:42] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:39:42] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:39:42] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:39:42] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:39:42] [Wrapper.py/ERROR]
[15:40:00] [Server thread/INFO]: <º9SurestTexas00ºr> i have a note in to the dev
eloper of the wrapper.
[15:40:00] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:40:00] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:40:00] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:40:00] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:40:00] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:40:00] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:40:00] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:40:00] [Wrapper.py/ERROR]
```

**Comment by benbaptist** [comment]
Yeah, something got wildly broken when the latest version on web mode. I
need to take a look

**Comment by suresttexas00** [comment]
OK.. I've decided to turn it back off for now anyway.

**Comment by benbaptist** [comment]
Is it possible that a plugin is causing this behaviour? I'm not 100% sure why your player objects are turning into booleans. Something funky is going on with one of the methods.

**Comment by suresttexas00** [comment]
Would `return True` or `return False` in the playerrawchat cause this?  I'm not sure that is what is happening because I have not had the chance to look into this yet...  The error is in the Web module, so I am not sure why a plugin would affect that...

**Comment by suresttexas00** [comment]
It appeared to me that the length of the chat message caused the error in web.py

**Comment by suresttexas00** [comment]
This an issue #130 are the same issue.  It occurs in line 50 of web.py.  My theory is as follows:

SOMEHOW the returning of a partial (just the "message", for instance) message payload or some other problem in the playerRawMessage event is causing the "player".username to become a boolean.

My code uses the playerRawMessage event to modify the players message to enable aliases and to filter some bad R rated language.
the last line of my code does this to return modifications to the typed message:
`		return payload["message"]`

Your Web.py code at line 50 is attempting the playerMessage event (why? versus playerRawMesssage..), which is where the conflict seems to occur.

Again, console output:
```
[15:33:41] [Server thread/INFO]: weinmueller[/127.0.0.1:50066] logged in with en
tity id 223 at (3529.650759741525, 67.0, 9667.9112915819)
{'player': <api.player.Player instance at 0x02C90418>}
[15:33:41] [Server thread/INFO]: weinmueller joined the game
[15:33:56] [Server thread/INFO]: <ºbJAKE5023ºr> did u get kicked
[15:33:56] [Wrapper.py/ERROR] Plugin 'Web' errored out when executing callback e
vent 'player.message':
[15:33:56] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:33:56] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[15:33:56] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:33:56] [Wrapper.py/ERROR]   File "Wrapper\web.py", line 50, in onPlayerMessa
ge
[15:33:56] [Wrapper.py/ERROR]     self.chatScrollback.append((time.time(), {"typ
e": "player", "payload": {"player": payload["player"].username, "message": paylo
ad["message"]}}))
[15:33:56] [Wrapper.py/ERROR] AttributeError: 'bool' object has no attribute 'us
ername'
[15:33:56] [Wrapper.py/ERROR]
[15:34:05] [Server thread/INFO]: <weinmueller> no
[15:35:04] [Wrapper.py/INFO] weinmueller executed: /home
[15:35:04] [Server thread/INFO]: Teleported weinmueller to 3530.1914, 63.0, 9667
.84453622
```

**Comment by suresttexas00** [comment]
Why are you taking a "player" and returning a "payload" that is just the payload["player"].username? or is that just supposed to return the username portion to "player"'s payload??

`self.chatScrollback.append((time.time(), {"type": "player", "payload": {"player": payload["player"].username, "message": payload["message"]}}))`

**Comment by suresttexas00** [comment]
not a wrapper problem.. this is vanilla server behavior:

"Chat Message
The default server will check the message to see if it begins with a '/'. If it doesn't, the username of the sender is prepended and sent to all other clients (including the original sender). If it does, the server assumes it to be a command and attempts to process it. A message longer than 100 characters will cause the server to kick the client. This change was initially done by allowing the client to not slice the message up to 119 (the previous limit), without changes to the server. For this reason, the vanilla server kept the code to cut messages at 119, but this isn't a protocol limitation and can be ignored."
