### ISSUE TITLE
Serialize Json

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#159]
I am trying to save a block loggers data to files:

```
		fnNew = ("%s-%d-break.log" % ((time.strftime("%d")), (int((time.strftime("%H")))/3) ))
		rawdata = self.globalset.breaklog
		with open("%s/%s.json" % ("logs/blocklog", fnNew) , "w") as f:
			f.write(json.dumps(rawdata))
```
The data from breaklog is as follows (from the file in the world/plugins/-id-/breaklog.json)
breaklog.json:
```
{"4f953255-6775-4dc6-a612-fb4230588eff": {"SurestTexas00": {"135,73,337": "14-20:42:55", "135,64,337": "14-20:43:05", "135,75,337": "14-20:42:53", "135,70,337": "14-20:42:59", "135,80,337": "14-20:42:48", "135,69,337": "14-20:43:00", "135,87,337": "14-20:42:41", "135,71,337": "14-20:42:58", "135,89,337": "14-20:42:38", "135,76,337": "14-20:42:52", "135,74,337": "14-20:42:54", "135,78,337": "14-20:42:50", "135,85,337": "14-20:42:43", "135,88,337": "14-20:42:40", "135,77,337": "14-20:42:51", "135,72,337": "14-20:42:57", "135,66,337": "14-20:43:03", "135,63,337": "14-20:43:07", "135,82,337": "14-20:42:46", "135,86,337": "14-20:42:42", "135,81,337": "14-20:42:47", "135,90,337": "14-20:42:37", "135,68,337": "14-20:43:01", "135,65,337": "14-20:43:04", "135,79,337": "14-20:42:49", "135,67,337": "14-20:43:02", "135,83,337": "14-20:42:45", "135,84,337": "14-20:42:44", "144,62,337": "14-20:44:03"}}, "log": {}}
```

The console says produces the following when I attempt this;
```
[21:26:09] [Wrapper.py/INFO] Loading plugin logger.py...
[21:26:09] [Wrapper.py/DEBUG] [Logger] Registered event 'player.dig'
[21:26:09] [Wrapper.py/DEBUG] [Logger] Registered event 'player.place'
[21:26:09] [Wrapper.py/DEBUG] [Logger] Registered command '/cube'
[21:26:09] [Wrapper.py/DEBUG] [Logger] Registered command '/wand'
[21:26:09] [Wrapper.py/INFO] Loading plugin simple.py...
[21:26:09] [Wrapper.py/DEBUG] [Simple] Registered help group 'Simple' with 30 co
mmands
[21:26:09] [Wrapper.py/DEBUG] [Simple] Registered event 'player.login'
[E21:26:09] [Wrapper.py/DEBUG] [Simple] Registered command 'spawn'xception in th
read Thread-13:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wrapper-plugins\logger.py", line 169, in _writeLog
    f.write(json.dumps(rawdata))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <storage.Storage instance at 0x0294B378> is not JSON serializable
```

I don't understand why this error occurs.. the data saves fine in your storage.Storage, but I can't save that data to my own file..

**Comment by suresttexas00** [comment]
I want to save the old breaklog periodically before it gets too huge; but still be able to search previous logs.

**Comment by suresttexas00** [comment]
This thing is just basically recording the coords and time of every block each player breaks.

**Comment by suresttexas00** [comment]
Maybe this is just being stupid and I should be using the getstorage method, maybe just use a different ID folder for the logs

**Comment by benbaptist** [comment]
The problem is that JSON's encoder sees the storage object and doesn't realize that it can iter through it like a dictionary, list, or tuple. Thus it just automatically fails.

**Comment by suresttexas00** [comment]
Then hopefully i can do this instead?

```
	def onSecond(self, payload):
		if time.time() - self.time > 60:  #60 = 1 minute
			self.time = time.time()
			Newfn = ("%s-%d-break.log" % ((time.strftime("%d")), (int((time.strftime("%H")))/3) ))
			if Newfn != self.fn:
				self.arch = self.api.getStorage(self.fn, True)
				self.arch = self.globalset.breaklog
				self.globalset.breaklog = {}
				self.arch.save()
				self.arch = self.api.getStorage(Newfn, True)
				self.fn = Newfn
```

**Comment by suresttexas00** [comment]
That does not work either, as i'm sure you might have guessed.  How to I copy the self.globalset.breaklog, save the new dataset, then dispose of it (so it does not keep periodicsaving)?

**Comment by suresttexas00** [comment]
well, i decided on the easier and much more fun "protection" route versus "find out who broke it" route.

**Comment by suresttexas00** [comment]
Old thread.  I'm sure it represents my own lack of understanding at the time.  I probably had a datatype wrong or some thing.
