### ISSUE TITLE
Problem in player.setResourcePack(self, url)

### ISSUE THREAD

**Issue by hespanha** [benbaptist/minecraft-wrapper#179]
The method setResourcePack() in the class Player, does not seem to work out. I believe the fix is to replace line 84 of player.py 
    self.client.send(0x3f, "string|bytearray", ("MC|RPack", url))
by either
   self.client.send(0x3f, "string|bytearray_short", ("MC|RPack", url))
for the server 1.7.10, or by
   player.client.send(0x48, "string|string", (url,"")) 
for the server 1.8.3.

This brings up the issue that the "pre-1.7-mode" variable in wrapper.properties is not quite adequate.
 Instead, one may need a variable "server-version" that can have 3 values: "pre-1.7", "1.7", and "1.8"

**Comment by benbaptist** [comment]
Ohai! 

Yeah, I accepted pull request #178 in but it apparently never actually pulled in (I always git merge manually). As for the pre-1.7 mode thing, that setting is only used for parsing the console text. In 1.7, the console output was changed quite a bit and so I had to make a new setting to allow pre-1.7 compatibility. This setting does not affect the proxy mode in any way - it uses protocol versions and automatically switches between 1.7 and 1.8 without an issue. 1.6 doesn't matter anyways - proxy mode doesn't support it as it's far more difficult to implement and the userbase for it is probably so small that it wouldn't matter much. 

I'm about to push my changes, so this should be fixed! Thanks for the report.

**Comment by benbaptist** [comment]
This has been fixed in build 99.

**Comment by hespanha** [comment]
This works for 1.8, but not for 1.7.10, where in response to 
     player.setResourcePack(url)
I'm getting

[00:57:09] [Wrapper.py/ERROR] Plugin 'hespanha.learning' errored out when executing callback event 'player.login':
[00:57:09] [Wrapper.py/ERROR] Traceback (most recent call last):
[00:57:09] [Wrapper.py/ERROR]   File "Wrapper/events.py", line 33, in callEvent
[00:57:09] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)
[00:57:09] [Wrapper.py/ERROR]   File "wrapper-plugins/Learning.py", line 264, in login
[00:57:09] [Wrapper.py/ERROR]     self.initPlayer(player);
[00:57:09] [Wrapper.py/ERROR]   File "wrapper-plugins/Learning.py", line 271, in initPlayer
[00:57:09] [Wrapper.py/ERROR]     player.setResourcePack(url)
[00:57:09] [Wrapper.py/ERROR]   File "Wrapper/api/player.py", line 94, in setResourcePack
[00:57:09] [Wrapper.py/ERROR]     if self.client.version <= 7:
[00:57:09] [Wrapper.py/ERROR] AttributeError: 'NoneType' object has no attribute 'version'
[00:57:09] [Wrapper.py/ERROR]

**Comment by hespanha** [comment]
PS. In the fix, line 93 of player.py reads
		if self.client.version < 7:
but it should probably be 
		if self.client.version <= 7:
However, this seems unrelated to the error "'NoneType' object has no attribute 'version'"

**Comment by benbaptist** [comment]
And you have proxy mode enabled? This is really odd that you're getting that error. It seems more like proxy mode is completely messed up under 1.7.10.
