### ISSUE TITLE
unable to work with forge 1.7.10 server

### ISSUE THREAD

**Issue by hespanha** [benbaptist/minecraft-wrapper#186]
I've tried to use the latest stable forge server 1.7.10 -- see log below for version, but I get an error on client complaining about "bad packet id 43". I was able to trace this down to the following line in proxy.py / Client.connect():
    self.send(0x2b, "ubyte|float", (1, 0))
The client error goes away if I comment this line, but then the client gets stuck waiting and eventually times out. 

[23:26:51] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1291 for Minecraft 1.7.10 loading
[23:26:51] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_40, running on Mac OS X:x86_64:10.10.3, installed at /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
[...]
[23:26:55] [Server thread/INFO]: Starting minecraft server version 1.7.10
[23:26:55] [Server thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[23:26:55] [Server thread/INFO] [FML]: MinecraftForge v10.13.2.1291 Initialized
[23:26:55] [Server thread/INFO] [FML]: Replaced 183 ore recipies

**Comment by hespanha** [comment]
PS. The problem arises in proxy mode. Everything works fine if I turn off proxy mode.

**Comment by suresttexas00** [comment]
What is your spigot mode value in wrapper.properties?... I don't think the code should have gotten that far unless there was a problem connecting.

I have no idea what Ben is doing there, but 0X2b is a "change game state" packet... ubyte 1 in this code would supposedly change to "End raining"

**Comment by hespanha** [comment]
I had spigot-mode=False, when I turn it to True, I get the following error:

[23:54:42] [Server thread/INFO]: Starting Minecraft server on *:25564
[23:54:42] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[23:54:42] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[23:54:42] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[23:54:42] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[23:54:43] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[23:54:43] [Server thread/INFO]: Preparing level "saves/Lucky Block Race"
[23:54:43] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[23:54:43] [Server thread/INFO] [FML]: Applying holder lookups
[23:54:43] [Server thread/INFO] [FML]: Holder lookups applied
[23:54:43] [Server thread/INFO] [FML]: Loading dimension 0 (saves/Lucky Block Race) (net.minecraft.server.dedicated.DedicatedServer@4d6bde)
[23:54:43] [Server thread/INFO] [FML]: Loading dimension 1 (saves/Lucky Block Race) (net.minecraft.server.dedicated.DedicatedServer@4d6bde)
[23:54:43] [Server thread/INFO] [FML]: Loading dimension -1 (saves/Lucky Block Race) (net.minecraft.server.dedicated.DedicatedServer@4d6bde)
[23:54:43] [Server thread/INFO]: Preparing start region for level 0
[23:54:44] [Server thread/INFO]: Preparing spawn area: 87%
[23:54:44] [Server thread/INFO]: Done (1.631s)! For help, type "help" or "?"
[23:54:44] [Wrapper.py/INFO] Server started
Client.parse(id=0) state=0
   server.version=5, packet.version=5, client.state=2
Client.parse(id=0) state=2
   packet.username=JoaoH
Error in the Client->Server method:
Traceback (most recent call last):
  File "src/proxy.py", line 567, in handle
    if self.parse(id) and self.server:
  File "src/proxy.py", line 340, in parse
    self.connect()
  File "src/proxy.py", line 231, in connect
    payload = "localhost\x00%s\x00%s" % (self.addr[0], self.uuid.hex)
AttributeError: 'NoneType' object has no attribute 'hex'

**Comment by benbaptist** [comment]
0x2b was a hack for cross-server mode so that when you connected to a secondary server, the rain would clear until the server sent its own change gamemode packet. Otherwise, if the lobby was raining and the secondary server wasn't, it would still appear to be raining. I don't know how to properly "reset" the Minecraft, so this is temporary until then.

**Comment by suresttexas00** [comment]
Superceded by #187.

**Comment by suresttexas00** [comment]
Can you say why you need proxy mode for a forge server?

**Comment by suresttexas00** [comment]
Track with #187 .

I hope to have both of these fixed in a week or two.  The solution will be to just let the forge client and forge server do their "thing" independent of wrapper.  Wrapper can detect the forge server and modify its proxy responses some.
