### ISSUE TITLE
build 100 - not able to log in

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#202]
```
[17:50:15] [Server thread/INFO]: ºbSurestTexas00ºr joined the game
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 952, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 874, in parse
    data = self.read("slot:data")
  File "Wrapper\proxy.py", line 1068, in read
    if type == "slot": result[name] = self.read_slot()
  File "Wrapper\proxy.py", line 1218, in read_slot
    id = self.read_short()
  File "Wrapper\proxy.py", line 1200, in read_short
    return struct.unpack(">h", self.read_data(2))[0]
error: unpack requires a string argument of length 2

Last packet IDs (Server->Client) before disconnection:
[('0x3e', 61), ('0x38', 37), ('0x38', 37), ('0x8', 34), ('0x44', 41), ('0x3', 17), ('0x2b',
6), ('0x2b', 6), ('0x2b', 6), ('0x30', 106)]
[17:50:15] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComponent{key='d
isconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connect
ion was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color
=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent
=null, insertion=null}}
[17:50:15] [Server thread/INFO]: ºbSurestTexas00ºr left the game
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 560, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 989, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 1013, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1163, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[17:50:37] [Wrapper.py/INFO] iiridellia logged in (UUID: 392ba6a4-4676-45b9-b20c-eaba76ed90c
8 | IP: 108.234.186.129)
[17:50:37] [Server thread/INFO]: iiridellia[/127.0.0.1:49391] logged in with entity id 160 a
t (-2543.4303522888395, 15.0, -1808.699999988079)
ProperWombat
[17:50:37] [Server thread/INFO]: iiridellia joined the game
Received Client Settings...
Sending self.clientSettings...
{'locale': 'en_US', 'chat_colors': False, 'displayed_skin_parts': 127, 'chat_mode': 0, 'view
_distance': 12}
Filtering 0x1a Packet: 160 | 9
Last packet IDs (Server->Client) before disconnection:
[('0x19', 4), ('0x17', 9), ('0x19', 4), ('0x12', 9), ('0x18', 18), ('0x19', 4), ('0x15', 7),
 ('0x19', 4), ('0x2f', 6), ('0x2f', 6)]
Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 934, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 991, in grabPacket
    payload = self.recv(length)
  File "Wrapper\proxy.py", line 1163, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[17:50:52] [Server thread/INFO]: iiridellia lost connection: TranslatableComponent{key='disc
onnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connection
 was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color=nu
ll, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=nu
ll, insertion=null}}
[17:50:52] [Server thread/INFO]: iiridellia left the game
[17:51:15] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a612-fb423058
8eff | IP: 68.50.227.172)
[17:51:15] [Server thread/INFO]: SurestTexas00[/127.0.0.1:49393] logged in with entity id 60
1 at (-3494.300000011921, 22.688856152470102, -8007.3770565643845)
ProperWombat
[17:51:15] [Server thread/INFO]: ºbSurestTexas00ºr joined the game
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 952, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 874, in parse
    data = self.read("slot:data")
  File "Wrapper\proxy.py", line 1068, in read
    if type == "slot": result[name] = self.read_slot()
  File "Wrapper\proxy.py", line 1218, in read_slot
    id = self.read_short()
  File "Wrapper\proxy.py", line 1200, in read_short
    return struct.unpack(">h", self.read_data(2))[0]
error: unpack requires a string argument of length 2

Last packet IDs (Server->Client) before disconnection:
[('0x3e', 61), ('0x38', 37), ('0x38', 37), ('0x8', 34), ('0x44', 41), ('0x3', 17), ('0x2b',
6), ('0x2b', 6), ('0x2b', 6), ('0x30', 106)]
[17:51:15] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComponent{key='d
isconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connect
ion was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color
=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent
=null, insertion=null}}
[17:51:15] [Server thread/INFO]: ºbSurestTexas00ºr left the game
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 560, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 989, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 1013, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1163, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[17:51:29] [Wrapper.py/INFO] iiridellia logged in (UUID: 392ba6a4-4676-45b9-b20c-eaba76ed90c
8 | IP: 108.234.186.129)
[17:51:29] [Server thread/INFO]: iiridellia[/127.0.0.1:49395] logged in with entity id 712 a
t (-2542.3883306788266, 15.0, -1807.4180637720835)
ProperWombat
[17:51:29] [Server thread/INFO]: iiridellia joined the game
Received Client Settings...
Sending self.clientSettings...
{'locale': 'en_US', 'chat_colors': False, 'displayed_skin_parts': 127, 'chat_mode': 0, 'view
_distance': 12}
/hault
[17:51:43] [Wrapper.py/ERROR] Invalid command hault
/halt
[17:51:49] [Wrapper.py/INFO] Stopping Minecraft server with reason: Halting server...
[17:51:49] [Wrapper.py/INFO] Disconnected from server: Halting server...
Exception in thread Thread-69:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Wrapper\proxy.py", line 666, in flush
    self.packet.flush()
  File "Wrapper\proxy.py", line 1040, in flush
    self.socket.send(packet)
error: [Errno 10053] An established connection was aborted by the software in your host mach
ine

[17:51:49] [Server thread/INFO]: iiridellia lost connection: TextComponent{text='Disconnecte
d', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined
=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
Exception in thread "Server Shutdown Thread" org.apache.logging.log4j.core.appender.Appender
LoggingException: Attempted to append to non-started appender ServerGuiConsole

Last packet IDs (Server->Client) before disconnection:
[('0x17', 9), ('0x19', 4), ('0x12', 9), ('0x1c', 22), ('0x13', 4), ('0x1a', 6), ('0x2f', 6),
 ('0x2f', 6), ('0x1a', 6), ('0x40', 21)]
[17:51:50] [Wrapper.py/INFO] Server stopped
[17:51:50] [Wrapper.py/ERROR] Disabling plugins...
```

**Comment by benbaptist** [comment]
Nobody can log in at all?

**Comment by suresttexas00** [comment]
not under that build. ^

**Comment by benbaptist** [comment]
So the client just disconnects then? Interesting. Seems like a case of something being parsed improperly (hence the failing to receive the short in one of the errors) or the socket is being disconnected from another reason, hence the inability to receive. This is probably a result of something else being try:except'd and being masked. Did this work without any plugins installed?

**Comment by benbaptist** [comment]
Dang! I just connected to start up my development setup and got this the first time I connected - http://s.benbaptist.com/wBPkZ 

I thought this bug was crushed. Grr. Although it might be a different packet causing it this time, since there's no 0x1a near it. 

```
[19:05:09] [Server thread/INFO]: §9benbaptist§r joined the game
Received Client Settings...
Sending self.clientSettings...
{'locale': 'en_US', 'chat_colors': False, 'displayed_skin_parts': 126, 'chat_mode': 0, 'view_distance': 15}
Last packet IDs (Server->Client) before disconnection:
[('0x33', 37), ('0x33', 32), ('0x35', 292), ('0x35', 337), ('0x35', 287), ('0x35', 259), ('0x35', 289), ('0x35', 290), ('0x35', 257), ('0x35', 6)]
```

Not sure if it's related. There's definitely some serious core issues with receving/parsing/sending packets properly that is only occasionally brought up, that cause these types of issues.

**Comment by suresttexas00** [comment]
well, i got it "working".. i.e. "i" was able to log on, and I was able to log on with another account.
1) Stopped wrapper
2) started new version WITHOUT plugins
3) loaded plugins to folder
4) logged on (successfully)
5) ran /reload in-game
6) logged of and on OK...

But i have other weird errors.  Everytime I kill myself or teleport , i get errors like this:
![image](https://cloud.githubusercontent.com/assets/10001762/8295772/fbb653a8-1915-11e5-9d92-f24b0c310aae.png)

They are "non-fatal" and I can log back in afterwards, but annoying.

**Comment by suresttexas00** [comment]
However, after dying in the end, it took 5 login attempts to get back on

**Comment by suresttexas00** [comment]
Still, over all, lets call this "better than before"

**Comment by suresttexas00** [comment]
NEVERMIND.. had to roll back!  Players getting kicked when they take damage!

**Comment by suresttexas00** [comment]
and then they could not get back on.

**Comment by benbaptist** [comment]
I hate Minecraft's protocol. :D

**Comment by benbaptist** [comment]
Alright, I can easily reproduce the eating/taking damage crashes. Gonna check those out right now.

**Comment by benbaptist** [comment]
Awesome. Two issues were happening. 0x1e and 0x1a again. Turns out, 0x1a was messing up because I was sending a varint instead of an int. I knew I was receiving this wrongly and fixed it, but I was still sending it wrongly. After that was fixed, I found my /heal command was causing me to get kicked about a second or so after using it. Then, I realized it's because after the status effects are gone, it sends the 0x1e packet which wasn't being sent right.

**Comment by benbaptist** [comment]
Another issue:
```
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "src/proxy.py", line 560, in handle
    id, original = self.packet.grabPacket()
  File "src/proxy.py", line 995, in grabPacket
    payload = zlib.decompress(payload)
error: Error -5 while decompressing data: incomplete or truncated stream
```

Pretty much any time the client sends g-zipped data, it breaks. i.e. adding a huge command to a command block, etc.

**Comment by suresttexas00** [comment]
Yes, I believe that is #114 which also caused bugs with large books

**Comment by suresttexas00** [comment]
For now, I am making single patches to build 99.  In fact, I think the only patch I need now is this one:

```
-						metalight = bytearray(self.packet.read_data(16*16*16))
+						if self.client.dimension == 0:
+							metalight = bytearray(self.packet.read_data(16*16*16))
```

  I'll probably also make my getPosition() consistent with yours.

all the entity and client setting stuff is not vital to get the server functional at the moment.

**Comment by suresttexas00** [comment]
Have you solved the gzip issue?

**Comment by benbaptist** [comment]
Yup - build 101 is awesome. I really hope it works well for you, because it seemed to work nearly flawlessly for me with about 6-7 hours of testing with multiple people. We were just screwing around playing with redstone and stuff and literally pretty much nothing went wrong. Super happy.

**Comment by suresttexas00** [comment]
Fixed
