### ISSUE TITLE
UUID set to False

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#212]
Again.

```
[17:33:16] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a612-fb423058
8eff | IP: x.x.x.x)
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 968, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 915, in parse
    properties = client.properties
AttributeError: 'UUID' object has no attribute 'properties'

Last packet IDs (Server->Client) before disconnection:
[('0x39', 10), ('0x9', 2), ('0x37', 52), ('0x3e', 56), ('0x3e', 62), ('0x3e', 63), ('0x3e',
48), ('0x3e', 61), ('0x38', 37), ('0x38', 35)]
[17:33:16] [Server thread/INFO]: SurestTexas00[/127.0.0.1:55702] logged in with entity id 63
69 at (3248.2478072654344, 84.91649650163917, 2687.9162149446906)
[17:33:16] [Wrapper.py/ERROR] UUID for SurestTexas00 is set to False. Proxy mode is <proxy.P
roxy instance at 0x05620328>. Please report this issue (and this line) to http://github.com/
benbaptist/minecraft-wrapper/issues
[17:33:16] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.global' errored out when exe
cuting callback event 'player.login':
[17:33:16] [Wrapper.py/ERROR] Traceback (most recent call last):
[17:33:16] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in callEvent
[17:33:16] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)
[17:33:16] [Wrapper.py/ERROR]   File "wrapper-plugins\global.py", line 176, in playerLogin
[17:33:16] [Wrapper.py/ERROR]     self.playerdata[playeruuid]["IP"] = playerIP
[17:33:16] [Wrapper.py/ERROR]   File "Wrapper\api\player.py", line 88, in getDimension
[17:33:16] [Wrapper.py/ERROR]     return self.getClient().dimension
[17:33:16] [Wrapper.py/ERROR] AttributeError: 'NoneType' object has no attribute 'dimension'

[17:33:16] [Wrapper.py/ERROR]
[17:33:16] [Server thread/INFO]: ºbSurestTexas00ºr joined the game
[17:33:16] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComponent{key='d
isconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connect
ion was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color
=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent
=null, insertion=null}}
[17:33:16] [Server thread/INFO]: ºbSurestTexas00ºr left the game
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 560, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 1005, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 1029, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1179, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

**Comment by benbaptist** [comment]
I think this will be fixed once I centralize all the UUID and auth code junk. It's just such a mess right now, and it's kept together with scotch tape.

**Comment by suresttexas00** [comment]
well.. don't fix it until you do my pull requests for these items and get me a build 106 to use: :D I'm running bubble gum on your scotch tape!

#209 - make groups inherit other groups nodes
#216 - Fix log rotation
Lastly... Code fix to undo last changes to icon schema - all that was broken in the old way was reading with "r" flag, versus "rb" (windows python is that picky.. as will be 3.x python on all platforms)

**Comment by benbaptist** [comment]
I'm not going to do that in 0.7.7 at all - this is a big thing and I really want a stable 0.7.7 and the only reason I delayed it is because there's issues with the log rotation on your system. I want to keep the icon code for now, though. #216 is in 106 now (in a modified way, hopefully it still works properly on your system). Will get 209 going.

**Comment by suresttexas00** [comment]
If you did not use "rb" for the read, I'll just go ahead and tell you; It won't work...

**Comment by benbaptist** [comment]
yes, I know, I can do the rb, but I still want the icon code in the same position. I do not want to change its location.

**Comment by suresttexas00** [comment]
Ok... I just thought you hated that because you would have to restart wrapper, etc...

**Comment by benbaptist** [comment]
No, because I eventually moved it into proxy mode which now can reload upon calling reloadProperties, which is automatically called upon every server boot and upon reloading server.properties for some other purpose. While I do like the idea of server-icon.png being real-time, I did think it through and it's probably better to reload it just once, because people could abuse the system and really tax the wrapper if they constantly spam it with MOTD requests.
