### ISSUE TITLE
Weird errors

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#213]
The plugin code:

```
    def _melt(self, player, args):
        if self._permitted(player, "region.player") is False:
            return
        p = self.getMemoryPlayer(player.username)
        dim = int(player.getDimension())
        if not dim == 0:
            player.message({"text": "Sorry, but you can't do this to the Nether or End.", "color": "red"})
            return
        playerposition = player.getPosition()
        coords = (playerposition[0]. playerposition[1], playerposition[2])
```

The error:

```
[21:31:59] [Server thread/INFO]: SurestTexas00[/127.0.0.1:56003] logged in with entity id 20
30 at (-10180.060533514272, 126.10382235892556, -6858.218018824077)
[21:31:59] [Server thread/INFO]: ºbSurestTexas00ºr joined the game
Sending self.clientSettings...
{'locale': 'en_US', 'chat_colors': False, 'displayed_skin_parts': 127, 'chat_mode': 0, 'view
_distance': 16}
[21:35:20] [Wrapper.py/INFO] SurestTexas00 executed: //meltsnow
[21:35:20] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.regions' errored out when ex
ecuting command: '<SurestTexas00> /{'callback': <bound method Main._melt of <regions.Main in
stance at 0x0B0EC2B0>>, 'permission': None}':
[21:35:20] [Wrapper.py/ERROR] Traceback (most recent call last):
[21:35:20] [Wrapper.py/ERROR]   File "Wrapper\commands.py", line 47, in playerCommand
[21:35:20] [Wrapper.py/ERROR]     command["callback"](payload["player"], payload["args"])
[21:35:20] [Wrapper.py/ERROR]   File "wrapper-plugins\regions.py", line 515, in _melt
[21:35:20] [Wrapper.py/ERROR]     coords = (playerposition[0]. playerposition[1], playerposi
tion[2])
[21:35:20] [Wrapper.py/ERROR] AttributeError: 'float' object has no attribute 'playerpositio
n'
[21:35:20] [Wrapper.py/ERROR]
```

This next error happened shortly before this. When these things start happening, I usually can only stop it by halting and restarting wrapper.

```
[21:24:48] [Server thread/INFO]: <ºbSurestTexas00ºr> did you read your mail?
[21:25:12] [Wrapper.py/INFO] SurestTexas00 executed: /gm 3
[21:25:12] [Server thread/INFO]: Set SurestTexas00's game mode to Spectator Mode
[21:25:24] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server
 overloaded? Running 3480ms behind, skipping 69 tick(s)
[21:29:30] [Wrapper.py/INFO] SurestTexas00 executed: /tp owenbl
[21:29:47] [Wrapper.py/INFO] SurestTexas00 executed: /gm 1
[21:29:47] [Server thread/INFO]: Set SurestTexas00's game mode to Creative Mode
[21:30:23] [Wrapper.py/INFO] SurestTexas00 executed: /gm 3
[21:30:23] [Server thread/INFO]: Set SurestTexas00's game mode to Spectator Mode
[21:31:16] [Wrapper.py/INFO] SurestTexas00 executed: /kick owenbl you must be lagged out.. l
ol
[21:31:16] [Wrapper.py/INFO] Disconnected from server: you must be lagged out.. lol by Sures
tTexas00
[21:31:16] [Server thread/INFO]: Kicked owenbl from the game: 'you must be lagged out.. lol
by SurestTexas00'
[21:31:16] [Server thread/INFO]: owenbl lost connection: TextComponent{text='you must be lag
ged out.. lol by SurestTexas00', siblings=[], style=Style{hasParent=false, color=null, bold=
null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, inser
tion=null}}
[21:31:16] [Server thread/INFO]: owenbl left the game
Last packet IDs (Server->Client) before disconnection:
[('0x0', 6), ('0x2f', 6), ('0x2f', 6), ('0x2f', 6), ('0x2f', 6), ('0x2f', 6), ('0x2f', 6), (
'0x2f', 6), ('0x2f', 6), ('0x40', 49)]
Last packet IDs (Server->Client) before disconnection:
[('0x3', 17), ('0x2f', 6), ('0x2f', 6), ('0x19', 4), ('0x19', 4), ('0x19', 4), ('0x2f', 6),
('0x2f', 6), ('0x19', 4), ('0x19', 4)]
Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 950, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 1007, in grabPacket
    payload = self.recv(length)
  File "Wrapper\proxy.py", line 1179, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[21:31:31] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComponent{key='d
isconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connect
ion was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color
=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent
=null, insertion=null}}
[21:31:31] [Server thread/INFO]: ºbSurestTexas00ºr left the game
Error in the Client->Server method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 588, in handle
    if self.parse(id) and self.server:
  File "Wrapper\proxy.py", line 296, in parse
    data = self.read("varint:version|string:address|ushort:port|varint:state")
  File "Wrapper\proxy.py", line 1075, in read
    if type == "ushort": result[name] = self.read_ushort()
  File "Wrapper\proxy.py", line 1218, in read_ushort
    return struct.unpack(">H", self.read_data(2))[0]
error: unpack requires a string argument of length 2
```

**Comment by benbaptist** [comment]
You had a period, not a comma...

```
coords = (playerposition[0]. playerposition[1], playerposition[2])
```

The second error seems far more specific or as if something was disconnecting you outside of the Wrapper, or the client disconnected itself or some other odd issue. I highly doubt it's reproducable or anything to worry about.

**Comment by suresttexas00** [comment]
EEK! period, not comma!
