### ISSUE TITLE
Weird disconnection that client does not see

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#225]
This error has been going on for a bit, but I caught this one in the act.  FYI, this was on a 15W31c test server, so, so far wrapper is OK.

Anyhow, the client has been getting disconnected from the server, but the client continues to be "on" the server and the player can continue to mine blocks, etc.  Once the player does get kicked. logs off, or notices that new chunks are not loading... once he logs back in, the player is at the same spot where the server-side disconnection first started.

```
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID c95cc6d
7-9b36-4a6d-be9f-2fc6de98bb12
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "src\proxy.py", line 268, in flush
    self.packet.flush()
  File "src\proxy.py", line 1083, in flush
    self.socket.send(self.sendCipher.encrypt(packet))
error: [Errno 10054] An existing connection was forcibly closed by the remote ho
st

[16:22:21] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a
612-fb4230588eff | IP: 68.50.227.172)
[16:22:21] [Wrapper.py/INFO] Disconnected from server: {u'text': u'You logged in
 from another location'}
[16:22:21] [Server thread/INFO]: SurestTexas00 lost connection: TextComponent{te
xt='You logged in from another location', siblings=[], style=Style{hasParent=fal
se, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickE
vent=null, hoverEvent=null, insertion=null}}
[16:22:21] [Server thread/INFO]: SurestTexas00 left the game
[16:22:21] [Server thread/INFO]: SurestTexas00[/127.0.0.1:55307] logged in with
entity id 3548 at (3573.9502884755148, 63.0, 9825.863677092852)
[16:22:21] [Server thread/INFO]: SurestTexas00 joined the game
Last packet IDs (Server->Client) before disconnection:
[('0x19', 4), ('0x19', 4), ('0x15', 7), ('0x19', 4), ('0x15', 7), ('0x19', 4), (
'0x15', 7), ('0x17', 9), ('0x19', 4), ('0x40', 48)]
```

These are some possible 15w31 errors that I have not seen before:
```
[16:19:40] [Server thread/WARN]: Tried to add entity with duplicate UUID 2df689a
5-2a8b-460d-8e31-beb0ca13b575
[16:19:40] [Server thread/WARN]: Tried to add entity with duplicate UUID 9fce55d
c-76ce-4693-80b8-b17ac45d1d36
Error in the Client->Server method:
Traceback (most recent call last):
  File "src\proxy.py", line 612, in handle
    if self.parse(id) and self.server:
  File "src\proxy.py", line 523, in parse
    data = self.read("position:position|byte:face|slot:item")
  File "src\proxy.py", line 1108, in read
    if type == "position": result[name] = self.read_position()
  File "src\proxy.py", line 1249, in read_position
    position = struct.unpack(">Q", self.read_data(8))[0]
error: unpack requires a string argument of length 8

[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID df6c990
f-2201-44a8-8da7-f5a648ecd5be
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID fd5a5a8
1-bd39-483e-9575-68764e1e148e
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID e045b79
b-52dc-4beb-9c64-256abd917a42
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID 522ce84
3-f6c9-4c8b-831d-423dc81f3f50
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID 9998669
6-e47d-40f1-9499-d211dc44e524
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID cab8c47
6-ca06-4119-a7b8-87d0f42fa706
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID 0351180
5-5b4b-421f-bb18-e9344a6105c3
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID b6a5f41
d-b431-40f2-8c48-908161f5a044
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID b87490d
b-512d-45d0-9d05-13511d6792b8
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID 6f08bb9
7-3591-410e-bf0e-9f91e115e1ba
[16:21:55] [Server thread/WARN]: Tried to add entity with duplicate UUID 6f08bb9
7-3591-410e-bf0e-9f91e115e1ba
```

**Comment by suresttexas00** [comment]
I'm opening a separate issue on this to cover the 1.9 aspect (i.e., from the added "slot" in 1.9)

**Comment by suresttexas00** [comment]
#226
