### ISSUE TITLE
1.9 slot changes (15w31c)

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#226]
New slot use (right click) silently disconnects player from server (but not wrapper?).. client is still "online".

```
[19:20:59] [Server thread/INFO]: SurestTexas00 joined the game
[19:21:17] [Server thread/INFO]: <SurestTexas00> dig...
[19:21:31] [Server thread/INFO]: <SurestTexas00> everything ok
[19:22:43] [Server thread/WARN]: Tried to add entity with duplicate UUID 79be8a4
6-7149-4c7e-a129-ef2fa193560e
[19:23:30] [Server thread/INFO]: <SurestTexas00> with sign in left hand slot
Error in the Client->Server method:
Traceback (most recent call last):
  File "src\proxy.py", line 612, in handle
    if self.parse(id) and self.server:
  File "src\proxy.py", line 523, in parse
    data = self.read("position:position|byte:face|slot:item")
  File "src\proxy.py", line 1108, in read
    if type == "position": result[name] = self.read_position()
  File "src\proxy.py", line 1249, in read_position
    position = struct.unpack(">Q", self.read_data(8))[0]
error: unpack requires a string argument of length 8
```
Disconnected at this point (but still "on").  once I disconnect and log back in and right click again...

```
[19:31:43] [Server thread/WARN]: Tried to add entity with duplicate UUID 82a19e6
6-00db-40cb-a00b-b3c21569e009
[19:33:13] [Server thread/WARN]: Tried to add entity with duplicate UUID 7c8f747
0-56b1-45ab-9084-cdae173c5797
Exception in thread Thread-22:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "src\proxy.py", line 268, in flush
    self.packet.flush()
  File "src\proxy.py", line 1083, in flush
    self.socket.send(self.sendCipher.encrypt(packet))
error: [Errno 10054] An existing connection was forcibly closed by the remote ho
st

[19:34:42] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a
612-fb4230588eff | IP: 68.50.227.172)
[19:34:42] [Wrapper.py/INFO] Disconnected from server: {u'text': u'You logged in
 from another location'}
[19:34:42] [Server thread/INFO]: SurestTexas00 lost connection: TextComponent{te
xt='You logged in from another location', siblings=[], style=Style{hasParent=fal
se, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickE
vent=null, hoverEvent=null, insertion=null}}
[19:34:42] [Server thread/INFO]: SurestTexas00 left the game
[19:34:42] [Server thread/INFO]: SurestTexas00[/127.0.0.1:56055] logged in with
entity id 6891 at (3577.7127954906396, 63.0, 9866.34341014116)
[19:34:42] [Server thread/INFO]: SurestTexas00 joined the game
Last packet IDs (Server->Client) before disconnection:
[('0x15', 6), ('0x19', 3), ('0x15', 6), ('0x15', 6), ('0x0', 6), ('0x19', 3), ('
0x19', 4), ('0x15', 7), ('0x19', 4), ('0x40', 48)]
Error in the Client->Server method:
Traceback (most recent call last):
  File "src\proxy.py", line 612, in handle
    if self.parse(id) and self.server:
  File "src\proxy.py", line 523, in parse
    data = self.read("position:position|byte:face|slot:item")
  File "src\proxy.py", line 1108, in read
    if type == "position": result[name] = self.read_position()
  File "src\proxy.py", line 1249, in read_position
    position = struct.unpack(">Q", self.read_data(8))[0]
error: unpack requires a string argument of length 8
```

**Comment by suresttexas00** [comment]
Not actually really sure what is going on here...

**Comment by benbaptist** [comment]
Possibly a packet change, although the latest snapshot has so many genuine protocol errors (ones that cause issues even on a 100% vanilla client+server setup) so I don't know if I should wait to try to fix issues or not.

**Comment by suresttexas00** [comment]
Agree.. close for now!
