### ISSUE TITLE
0 len packet followed by Bad file descriptor

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#228]
These two errors continue to baffle me.  I am able to log in for like 1 second before getting disconnected. 

What causes a "zero length" packet and is _that_ what _causes_ the disconnection?

... and why do these two errors always go together?

```
[23:48:07] [Server thread/INFO]: SurestTexas00 joined the game
Received Client Settings...
Sending self.clientSettings...
{'main_hand': 1, 'chat_colors': False, 'chat_mode': 0, 'locale': 'en_US', 'displ
ayed_skin_parts': 127, 'view_distance': 16}
Traceback (most recent call last):
  File "src\proxy.py", line 1003, in handle
    id, original = self.packet.grabPacket()
  File "src\proxy.py", line 1052, in grabPacket
    length = self.unpack_varInt()
  File "src\proxy.py", line 1082, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "src\proxy.py", line 1234, in recv
    raise EOFError("Packet was zero length, disconnecting")
EOFError: Packet was zero length, disconnecting

Last packet IDs (Server->Client) before disconnection:
[('0x1f', 7), ('0x19', 4), ('0x19', 4), ('0x19', 4), ('0x19', 4), ('0x3', 17), (
'0x19', 4), ('0x19', 4), ('0x19', 4), ('0x0', 6)]
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "src\proxy.py", line 613, in handle
    id, original = self.packet.grabPacket()
  File "src\proxy.py", line 1058, in grabPacket
    dataLength = self.unpack_varInt()
  File "src\proxy.py", line 1082, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "src\proxy.py", line 1232, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[23:48:09] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComp
onent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler
.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + l
ength(8) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 8, widx: 11, cap: 11
)], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null
, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=
null}}
[23:48:09] [Server thread/INFO]: SurestTexas00 left the game
```

**Comment by benbaptist** [comment]
It's not causing the disconnection. It's a result of the disconnection. You're looking at the wrong parts of this for errors - the error lies on the server's output - as you can see
```
SurestTexas00 lost connection: TranslatableComp
onent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler
.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + l
ength(8) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 8, widx: 11, cap: 11
)]

i.e. this is a result of a packet being sent improperly by the client or server, and is causing the server to flip out and disconnect.

**Comment by suresttexas00** [comment]
DO you know enough about these terms to have an idea what sort of packet is wa?

**Comment by suresttexas00** [comment]
I always get the the Errno9 bad file descriptor when people disconnect normally (which is annoying).  However, the "EOFError: Packet was zero length" is always the result of an error, which is why I thought it might be the cause.
