### ISSUE TITLE
Right Clicking enchanted items kicks player permanently

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#231]
I tested it twice on my self and the player who brought it my attention.  The only fix is to delete the playeruuid.dat file.

attached are the files;
https://www.dropbox.com/s/p2fx28g3lflr3el/3269fd15-5be9-3c2a-af6c-12147a760f78_2.dat?dl=0

https://www.dropbox.com/s/vgisa6nkq2nhzuf/e5c341b1-dffa-3793-8c5c-63ec51f72db9_2.dat?dl=0

**Comment by suresttexas00** [comment]
Please add labels "Emergency" "Proxy mode"? Still does this on build 107.

**Comment by suresttexas00** [comment]
```[22:04:19] [Wrapper.py/INFO] Server started
[22:04:25] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a612-fb4230588eff | IP: 6
8.50.227.172)
Sending 0x2B...
[22:04:25] [Server thread/INFO]: SurestTexas00[/127.0.0.1:52886] logged in with entity id 139 at (1593.1
047856789685, 69.0, 464.1529057363117)
[22:04:26] [Server thread/INFO]: ºbSurestTexas00ºr joined the game
Sending self.clientSettings...
{'locale': 'en_US', 'chat_colors': False, 'displayed_skin_parts': 127, 'chat_mode': 0, 'view_distance':
16}
{'count': 1, 'id': 145, 'damage': 2}
[22:04:51] [Wrapper.py/INFO] SurestTexas00 executed: /gm 0
[22:04:51] [Server thread/INFO]: Set SurestTexas00's game mode to Survival Mode
{'count': 1, 'id': 145, 'damage': 2}
{'count': 1, 'id': 145, 'damage': 2}
{'count': 1, 'id': 311, 'damage': 0}
{'count': 1, 'id': 311, 'damage': 0}
{'count': 1, 'id': 311, 'damage': 0}
{'count': 1, 'id': 311, 'damage': 0}
{'count': 1, 'id': 311, 'damage': 0}
{'count': 1, 'id': 311, 'damage': 0}
{'count': 1, 'id': 311, 'damage': 0}
{'count': 1, 'id': 311, 'damage': 0}
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 1003, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 924, in parse
    data = self.read("slot:data")
  File "Wrapper\proxy.py", line 1119, in read
    if type == "slot": result[name] = self.read_slot()
  File "Wrapper\proxy.py", line 1269, in read_slot
    id = self.read_short()
  File "Wrapper\proxy.py", line 1251, in read_short
    return struct.unpack(">h", self.read_data(2))[0]
  File "Wrapper\proxy.py", line 1230, in read_data
    self.obj.disconnect("Received no data or less data than expected - connection closed")
AttributeError: Server instance has no attribute 'disconnect'

Last packet IDs (Server->Client) before disconnection:
[('0x15', 7), ('0x15', 7), ('0x15', 7), ('0x19', 4), ('0x15', 7), ('0x2f', 6), ('0x2f', 6), ('0x2f', 6),
 ('0x2f', 6), ('0x30', 150)]
Failed to grab packet (CLIENT):
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 589, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 1040, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 1064, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1214, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[22:05:28] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComponent{key='disconnect.ge
nericReason', args=[Internal Exception: java.io.IOException: An existing connection was forcibly closed
by the remote host], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, under
lined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[22:05:28] [Server thread/INFO]: ºbSurestTexas00ºr left the game
```
right clicked a chestplate with blast protection IV.  This only happened when the armor slot was empty.

**Comment by suresttexas00** [comment]
Disgusting Fix to allow me to get back on without deleting player file:
#232

**Comment by suresttexas00** [comment]
We fixed this somewhere along the line recently, I believe (either from the disabling of the packet or sasszems window and nbt parsing fixes..
