### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by xxnovosxx** [benbaptist/minecraft-wrapper#241]
[15:18:06] [Wrapper.py/INFO] Wrapper.py started - Version 0.7.7 (development build #108)
[15:18:06] [Wrapper.py/INFO] Loading plugins...
[15:18:06] [Wrapper.py/INFO] Starting server...
[15:18:06] [Wrapper.py/ERROR] Wrapper.py crashed - stopping server to be safe
[15:18:06] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:18:06] [Wrapper.py/ERROR] File "Wrapper.py/main.py", line 360, in 
[15:18:06] [Wrapper.py/ERROR] wrapper.start()
[15:18:06] [Wrapper.py/ERROR] File "Wrapper.py/main.py", line 168, in start
[15:18:06] [Wrapper.py/ERROR] self.server.handle_server()
[15:18:06] [Wrapper.py/ERROR] File "Wrapper.py/server.py", line 276, in handle_server
[15:18:06] [Wrapper.py/ERROR] self.proc = subprocess.Popen(self.args, stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
[15:18:06] [Wrapper.py/ERROR] File "/usr/lib/python2.7/subprocess.py", line 710, in init
[15:18:06] [Wrapper.py/ERROR] errread, errwrite)
[15:18:06] [Wrapper.py/ERROR] File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
[15:18:06] [Wrapper.py/ERROR] raise child_exception
[15:18:06] [Wrapper.py/ERROR] OSError: [Errno 2] No such file or directory
[15:18:06] [Wrapper.py/ERROR]
[15:18:06] [Wrapper.py/ERROR] Disabling plugins...
[15:18:06] [Wrapper.py/INFO] Stopping Minecraft server with reason: Wrapper.py crashed - please contact the server host instantly

i do not know what i did wrong and when do: pip install requests pkg_resources pycrypto i get the following error

Could not find any downloads that satisfy the requirement pkg-resources
Cleaning up...
No distributions at all found for pkg-resources
Storing debug log for failure in /root/.pip/pip.log

/usr/bin/pip run on Mon Oct 26 13:09:42 2015
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
Downloading/unpacking pkg-resources
Getting page https://pypi.python.org/simple/pkg_resources/
Could not fetch URL https://pypi.python.org/simple/pkg_resources/: 404 Client Error: Not Found
Will skip URL https://pypi.python.org/simple/pkg_resources/ when looking for download links for pkg-resources
Getting page https://pypi.python.org/simple/
Real name of requirement pkg_resources is pkg-resources
URLs to search for versions for pkg-resources:

https://pypi.python.org/simple/pkg-resources/ Getting page https://pypi.python.org/simple/pkg-resources/ Could not fetch URL https://pypi.python.org/simple/pkg-resources/: 404 Client Error: Not Found Will skip URL https://pypi.python.org/simple/pkg-resources/ when looking for download links for pkg-resources Could not find any downloads that satisfy the requirement pkg-resources Cleaning up... Removing temporary dir /tmp/pip_build_root... No distributions at all found for pkg-resources Exception information: Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main status = self.run(options, args) File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle) File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files url = finder.find_requirement(req_to_install, upgrade=self.upgrade) File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement raise DistributionNotFound('No distributions at all found for %s' % req) DistributionNotFound: No distributions at all found for pkg-resources

**Comment by suresttexas00** [comment]
Just a suggestion... don't try installing all the packages at once.  That pkg_resources thing seems so familiar... search for that term on stack exchange.

**Comment by suresttexas00** [comment]
I know you are Linux, but try following the windows steps in the readme.  It may help you see exactly where the problem is.  I think pkg_resources may not be a 'real' thing, but actually a part of setuptools...

**Comment by benbaptist** [comment]
The problem appears to be with not being able to run the command configured in wrapper.properties.

Of course, make sure java is installed and is running the right command to execute your jar file correctly. If all is well, and copying & pasting the command from the wrapper.properties file works, then there's possibly a bug with Wrapper.py.

**Comment by suresttexas00** [comment]
closed due to inactivity or response from OP.
