### ISSUE TITLE
Accended letters causes error

### ISSUE THREAD

**Issue by Sasszem** [benbaptist/minecraft-wrapper#242]
I'm Hungarian, so I'm playing from Hungary. For some reason, when I login into my server, I see that my game sends data with hungarien text in it, & that causes errors in Wrapper.py.

I can not paste the full log, but I can tell that it says the error at Wrapper.py\storage.py line 59, in function save: f.write(json.dump(self.data))
...
UnicodeDecodeError: 'utf8' codec can 't decode byte 0xf6 in position 2: ordinal not in range(128)

What shoud I do? Change system language(MC's language is set to ENGLISH), or manually edit Wrapper.py

Note: I've tried to edit W.py manually, but for some strange reason, still not work. Becouse I think it's python's fault, I've asked a q. at StackOwerflow

**Comment by Sasszem** [comment]
I was able to record log:

[21:56:17] [Wrapper.py/INFO] Wrapper.py started - Version 0.7.6 (stable)
[21:56:17] [Wrapper.py/INFO] Loading plugins...
[21:56:17] [Wrapper.py/INFO] Starting server...
[21:56:22] [Server thread/INFO]: Starting minecraft server version 1.8.8
[21:56:22] [Server thread/INFO]: Loading properties
[21:56:22] [Server thread/INFO]: Default game type: SURVIVAL
[21:56:22] [Server thread/INFO]: Generating keypair
[21:56:22] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:56:22] [Server thread/INFO]: Using default channel type
[21:56:23] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:56:23] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:56:23] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[21:56:23] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:56:23] [Server thread/INFO]: Preparing level "world"
[21:56:23] [Server thread/INFO]: Preparing start region for level 0
[21:56:23] [Server thread/INFO]: Done (0,826s)! For help, type "help" or "?"
[21:56:24] [Wrapper.py/INFO] Server started
[21:56:26] [Server thread/INFO]: Sasszem[/127.0.0.1:52226] logged in with entity id 309 at (118.12095411450942, 87.47075120835132, 403.92822429072436)
[21:56:26] [Server thread/INFO]: Sasszem joined the game
[21:56:36] [Server thread/INFO]: <Sasszem> I'm logged in
Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

[21:58:08] [Server thread/INFO]: <Sasszem> Waiting 4 server to call periodicSave
Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

[21:58:32] [Server thread/INFO]: <Sasszem> Becouse of redirection the output to file, I can't see messages
Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

Traceback (most recent call last):
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 40, in periodicSave
    self.save()
  File "C:\Users\User\Desktop\server\Wrapper.py\storage.py", line 59, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

[21:59:42] [Server thread/INFO]: <Sasszem> I hope that waiting was enught
[21:59:45] [Server thread/INFO]: [Sasszem: Stopping the server]
[21:59:45] [Server thread/INFO]: Stopping server
[21:59:45] [Server thread/INFO]: Saving players
[21:59:45] [Server thread/INFO]: Sasszem lost connection: TextComponent{text='Server closed', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[21:59:45] [Server thread/INFO]: Sasszem left the game
[21:59:45] [Server thread/INFO]: Saving worlds
[21:59:45] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[21:59:45] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[21:59:45] [Server thread/INFO]: Saving chunks for level 'world'/The End
[21:59:46] [Server Shutdown Thread/INFO]: Stopping server
[21:59:46] [Server Shutdown Thread/INFO]: Saving players
[21:59:46] [Server Shutdown Thread/INFO]: Saving worlds
[21:59:46] [Server Shutdown Thread/INFO]: Saving chunks for level 'world'/Overworld
[21:59:46] [Wrapper.py/INFO] Server stopped
[21:59:46] [Wrapper.py/ERROR] Disabling plugins...

**Comment by suresttexas00** [comment]
From experience, this is probably related to a plugin you are running.  Specifically, your plugin may be storing data in the the getStorage() method.  When wrapper attempts periodically save it, the error occurs.  The error happens because whatever you are saving is not Json complaint...


That's been my experience with these errors, anyway.


You can verify this is a wrapper storage item or a plugin by disabling your plugins and trying to run...


________________________________

**Comment by Sasszem** [comment]
I had fixed it by changing the encoding, now it works fine.
If you want, I'll send you my version of storage.py
There's another problem, but it's different, & I'll open a new issue.

2015.11.10. 1:05 keltezéssel, Surest Texas írta:

**Comment by suresttexas00** [comment]
I think we will all be interested.  I have noticed issues with getStorage objects.


________________________________

**Comment by Sasszem** [comment]
Here's my code, it works fine for me:
storage.py

**import json, os, threading, time, copy, traceback
import sys
reload(sys)
sys.setdefaultencoding("ISO-8859-1")
class Storage:
     def __init__(self, name, isWorld=None, root="wrapper-data/json"):
         self.name = name
         self.root = root

         self.data = {}
         self.dataOld = {}
         self.load()
         self.abort = False
         self.time = time.time()

         t = threading.Thread(target=self.periodicSave, args=())
         t.daemon = True
         t.start()
     def __del__(self):
         self.abort = True
         self.save()
     def __getitem__(self, index):
         if not type(index) == str:
             raise Exception("A string must be passed to the stuff")
         return self.data[index]
     def __setitem__(self, index, value):
         if not type(index) == str:
             raise Exception("A string must be passed to the stuff")
         self.data[index] = value
         return self.data[index]
     def __delattr__(self, index):
         if not type(index) == str:
             raise Exception("A string must be passed to the stuff")
         del self.data[index]
     def __iter__(self):
         for i in self.data:
             yield i
     def periodicSave(self):
         while not self.abort:
             if time.time() - self.time > 10:
                 if not self.data == self.dataOld:
                     try:
                         self.save()
                     except:
                         print traceback.format_exc()
                     self.time = time.time()
             time.sleep(1)
     def load(self):
         l = ""
         for i in self.root.split("/"):
             l += i + "/"
             if not os.path.exists(l):
                 try: os.mkdir(l)
                 except: pass
         if not os.path.exists("%s/%s.json" % (self.root, self.name)):
             self.save()
         with open("%s/%s.json" % (self.root, self.name), "r") as f:
             self.data = json.loads(f.read(),"ISO-8859-1")
         self.dataOld = copy.deepcopy(self.data)
     def save(self):
         with open("%s/%s.json" % (self.root, self.name) , "w") as f:
             f.write(json.dumps(self.data,ensure_ascii=False))
         self.flush = False
     def key(self, key, value=None):
         if value == None:
             return self.getKey(key)
         else:
             self.setKey(key, value)
     def getKey(self, key):
         if key in self.data:
             return self.data[key]
         else:
             return None
     def setKey(self, key, value=None):
         if value == None:
             if key in self.data: del self.data[key]
         else:
             self.data[key] = value
         self.flush = True**


I've only modified the 2-4th, 58th & 62th lines to adapt it to 
ISO-8859-1 encoding

2015.11.10. 21:34 keltezéssel, Surest Texas írta:

**Comment by suresttexas00** [comment]
I have not looked at this code yet to compare it to the original, but if it corrects some error in wrapper's storage system, you should create a pull request for it (even if Ben may opt to manually merge it)


________________________________

**Comment by Sasszem** [comment]
I've did a pull request with the modification. It allows you to set the encoding that JSON uses in the config. I've modified the minecraft.py, storage.py & the config.py files.
