### ISSUE TITLE
Python CPU usage creeps up over time

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#276]
I am noticing that when i first start wrapper (and even after a number of players have joined) that the CPU usage runs between 2 and 5%.  Over a period of hours, this creeps up to around 30-50%.  After some time, the CPU usage becomes 80-95%.  I've been restarting wrapper at this point, but I believe this also coincides with the point at which wrapper starts behaving erratically (UUID problems, etc).

**Comment by suresttexas00** [comment]
here is a screenshot showing the before and after a wrapper restart (same number of players; in fact the same ones):
<a href="http://i.imgur.com/Y20AohU.png">
  <img src="http://imgur.com/Y20AohUl.png" />
</a>

**Comment by suresttexas00** [comment]
and here we are 3 hours later:

<a href="http://i.imgur.com/c0aWKD6.png">
  <img src="http://imgur.com/c0aWKD6l.png" />
</a>

**Comment by suresttexas00** [comment]
I noticed today that the usage increased in "spikes":
![image](https://cloud.githubusercontent.com/assets/10001762/13203988/1102e5a0-d892-11e5-8366-339ca2826ddf.png)

each of these spikes is associated with a player disconnection:
```

Last packet IDs (Server->Client) of player KateGirl_21 before disconnection: 
[('0x39', 8), ('0x26', 12), ('0x34', 4), ('0x25', 10), ('0x39', 8), ('0x3b', 9), ('0x25', 10), ('0x39', 8), ('0x26', 12), ('0x34', 4)]

Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "/home/surest/vanilla/wrapper/proxy.py", line 1223, in handle
    id, original = self.packet.grabPacket()
  File "/home/surest/vanilla/wrapper/proxy.py", line 1309, in grabPacket
    payload = self.recv(length)
  File "/home/surest/vanilla/wrapper/proxy.py", line 1541, in recv
    d = self.socket.recv(length)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[11:46:15] [Server thread/INFO]: KateGirl_21 lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[11:46:15] [Server thread/INFO]: KateGirl_21 left the game
Last packet IDs (Server->Client) of player DiamondNighthawk before disconnection: 
[('0x3e', 10), ('0x39', 10), ('0x34', 4), ('0x34', 4), ('0x44', 17), ('0x34', 4), ('0x34', 4), ('0x34', 4), ('0x3e', 10), ('0x39', 10)]

Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "/home/surest/vanilla/wrapper/proxy.py", line 1223, in handle
    id, original = self.packet.grabPacket()
  File "/home/surest/vanilla/wrapper/proxy.py", line 1309, in grabPacket
    payload = self.recv(length)
  File "/home/surest/vanilla/wrapper/proxy.py", line 1541, in recv
    d = self.socket.recv(length)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[11:46:20] [Server thread/INFO]: DiamondNighthawk lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[11:46:20] [Server thread/INFO]: DiamondNighthawk left the game
[11:46:22] [Server thread/INFO]: <lique07> no for the moment
[11:46:27] [Server thread/INFO]: <nolan2789> Ok
Last packet IDs (Server->Client) of player Cuth71 before disconnection: 
[('0x25', 10), ('0x26', 12), ('0x34', 4), ('0x25', 10), ('0xf', 283), ('0x26', 12), ('0x34', 4), ('0x3b', 9), ('0x25', 10), ('0x34', 4)]

Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "/home/surest/vanilla/wrapper/proxy.py", line 1223, in handle
    id, original = self.packet.grabPacket()
  File "/home/surest/vanilla/wrapper/proxy.py", line 1309, in grabPacket
    payload = self.recv(length)
  File "/home/surest/vanilla/wrapper/proxy.py", line 1541, in recv
    d = self.socket.recv(length)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[11:46:27] [Server thread/INFO]: Cuth71 lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[11:46:27] [Server thread/INFO]: Cuth71 left the game
```

**Comment by JasonBristol** [comment]
So CPU usage spikes after a DC and doesn't fade? How does memory usage look during these cases?

**Comment by suresttexas00** [comment]
regarding memory; memory is generally pretty stable... it does creep slowly, but much less than CPU usage.

I agree, I think the threading IS a large part of the problem.

**Comment by benbaptist** [comment]
Indeed. The way I abused threads is a massive, ugly part of Wrapper.py. honestly,  I don't think threads are very appropriate at all in this scenario - using epoll/poll/select in most of these cases is more appropriate, as I was mentioning earlier in a different thread. Making a system that uses epoll, falls back on poll, which falls back on select/Windoze's alternative to that. This can be used to read and write to almost anything, including log I/O, subprocess communication (IIRC), and all sockets throughout the wrapper.

**Comment by suresttexas00** [comment]
Can we get this moving, at least in some steps:
1) Get 1.9 ready.
2) Correct the threads as JasonBristol suggests
3) then refactor with epoll/poll.

**Comment by suresttexas00** [comment]
Summarizing: We are at step 2) now. Maybe we can start by getting the log file handles closed.

**Comment by JasonBristol** [comment]
I can include log handling fixes with some of the threading work in my next PR if that is easier, should be pretty straightforward

**Comment by suresttexas00** [comment]
Here is another source of problems.  I thought this statement would not run because i mistakenly thought the wrold variable was not set:
```
                # we are not going to do all the parsing work unless we are storing the entity data
                # Storing this entity data has other issues; like removing stale items or "dead" items.
                if not self.wrapper.javaserver.world:
                    self.log.trace("(PROXY SERVER) -> did not parse SPAWN_MOB packet.")
                    return True
```
well, I was wrong, it is; and we ARE parsing all that entity data... and we __Are not__ removing stale or dead entities.

**Comment by suresttexas00** [comment]
I can't prove it yet because I have not tested this on my server, but I believe this was caused by entity parsing.  Overtime, the entity data grew larger and larger... it also correlates with the fact that it occurs in a player login and fails to subside substantially after a player logoff (as a player logs in, all it's entities in the loaded chunks get parsed and added to world.entity).... So this is possibly addressed by parsing the entity destructions... 

partially/possibly.  It occurs to me that entities in unloaded chunks due to a player disconnect will not be part of the "destroyed" entities list.

Since entities send activity packets periodically, we could add a time field to them and delete on inactivity as well.

**Comment by suresttexas00** [comment]
And yes, I DO know that entities never get destroyed, even when the client server connection that created them is logged off...  This alone, given enough time, will grow memory enough to crash.

**Comment by suresttexas00** [comment]
Fixed

**Comment by benbaptist** [comment]
Woohoo!
