### ISSUE TITLE
problem with self.data.save()

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#54]
I narrowed this error to being caused by the plugin statement self.data.save()

C:\Users\JRUSSELL\Desktop\vanilla>python Wrapper.py
[18:41:21] [Wrapper.py/INFO] Wrapper.py started - Version 0.7.4 (development bui
ld #61)
[18:41:21] [Wrapper.py/INFO] Loading plugins...
[18:41:21] [Wrapper.py/INFO] Loading plugin Essentials.py...
[18:41:21] [Wrapper.py/DEBUG] [Essentials] Registered all of its commands.................
[18:41:21] [Wrapper.py/DEBUG] [Essentials] Registered all its events
[18:41:21] [Wrapper.py/INFO] Starting server...
[18:41:25] [Server thread/INFO]: Starting minecraft server version 1.8.1
....
[18:41:27] [Server thread/INFO]: Preparing spawn area: 95%
[18:41:27] [Server thread/INFO]: Done (1.144s)! For help, type "help" or "?"
[18:41:27] [Wrapper.py/INFO] Server started
[18:41:55] [Wrapper.py/INFO] SurestTexas00 logged in ...
[18:41:55] [Server thread/INFO]: SurestTexas00[/127.0.0.1:52940] logged in with
entity id 69 at (-4.190475225733941, 64.0, 59.36807096897444)
{'player': <api.player.Player instance at 0x02953DF0>}
[18:41:55] [Server thread/INFO]: SurestTexas00 joined the game
Last packet IDs (Server->Client) before disconnection:
[('0x19', 4), ('0x15', 7), ('0x1c', 7), ('0x19', 4), ('0x17', 9), ('0x19', 4), (
'0x17', 9), ('0x19', 4), ('0x17', 9), ('0x19', 4)]
Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "Wrapper.py\proxy.py", line 757, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper.py\proxy.py", line 817, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper.py\proxy.py", line 841, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper.py\proxy.py", line 987, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

Last packet IDs (Server->Client) before disconnection:
[('0x19', 4), ('0x15', 7), ('0x1c', 7), ('0x19', 4), ('0x17', 9), ('0x19', 4), (
'0x17', 9), ('0x19', 4), ('0x17', 9), ('0x19', 4)]
[18:42:09] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComp
onent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOExcept
ion: An existing connection was forcibly closed by the remote host], siblings=[]
, style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=nu
ll, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[18:42:09] [Server thread/INFO]: SurestTexas00 left the game

**Comment by suresttexas00** [comment]
sorry to be using build 61.. it's the last one that can run on my machine.
