### ISSUE TITLE
How to get UUIDs

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#55]
I've created my plugin to store peoples "/sethome", but right now it saves their home in the storage container indexed by their username.. usernames which might change in some future version.  I want to store their info under the UUID.  However, I only see  a player api method called lookupUUID that returns the username.. but I already have the name from player.username, so I am scratching my head as to why I need lookupUUID(uuid)???  Where do I get UUID's of the player in question (who is typing /home or /sethome  ?

**Comment by benbaptist** [comment]
It should be as simple as using player.uuid to get their UUID.

**Comment by suresttexas00** [comment]
yes, player.uuid did work... I did not know about that.

**Comment by suresttexas00** [comment]
However, now that I am using UUIDs for the data storage, the data is not being saved to disk by self.data.save().  Truthfully, this was going to be the next issue i would post, but although I have been getting errors from the save process, the data still saved properly until now.  I have been getting these error messages:

[2015-01-08 12:08:18] [Wrapper.py/INFO] SurestTexas00 executed: /spawn 
[2015-01-08 12:08:22] [Wrapper.py/INFO] SurestTexas00 executed: /home 
[2015-01-08 12:08:22] [Simple Plugin/DEBUG] home used '4f953255-6775-4dc6-a612-fb4230588eff' as the UUID for that command
[2015-01-08 12:08:22] [Simple Plugin/DEBUG] home TP'd '4f953255-6775-4dc6-a612-fb4230588eff' AKA 'SurestTexas00' to '(225.85312061264128, 64.0, -60.39294926429588)'
[2015-01-08 12:08:25] [Wrapper.py/INFO] SurestTexas00 executed: /spawn 
[2015-01-08 12:09:08] [Wrapper.py/INFO] Stopping Minecraft server with reason: Halting server...
[2015-01-08 12:09:09] [Wrapper.py/INFO] Server stopped
[2015-01-08 12:09:09] [Wrapper.py/ERROR] Disabling plugins...
[2015-01-08 12:09:09] [Wrapper.py/ERROR] Error while disabling plugin 'com.suresttexas00.plugins.simple'
[2015-01-08 12:09:09] [Wrapper.py/ERROR] Traceback (most recent call last):
[2015-01-08 12:09:09] [Wrapper.py/ERROR]   File "C:\Users\JRUSSELL\Desktop\vanilla\Wrapper\__main__.py", line 83, in unloadPlugin
[2015-01-08 12:09:09] [Wrapper.py/ERROR]     self.plugins[plugin]["main"].onDisable()
[2015-01-08 12:09:09] [Wrapper.py/ERROR]   File "wrapper-plugins\simple.py", line 49, in onDisable
[2015-01-08 12:09:09] [Wrapper.py/ERROR]     self.data.save()
[2015-01-08 12:09:09] [Wrapper.py/ERROR]   File "Wrapper\storage.py", line 56, in save
[2015-01-08 12:09:09] [Wrapper.py/ERROR]     f.write(json.dumps(self.data))
[2015-01-08 12:09:09] [Wrapper.py/ERROR]   File "C:\Python27\lib\json\__init__.py", line 243, in dumps
[2015-01-08 12:09:09] [Wrapper.py/ERROR]     return _default_encoder.encode(obj)
[2015-01-08 12:09:09] [Wrapper.py/ERROR]   File "C:\Python27\lib\json\encoder.py", line 207, in encode
[2015-01-08 12:09:09] [Wrapper.py/ERROR]     chunks = self.iterencode(o, _one_shot=True)
[2015-01-08 12:09:09] [Wrapper.py/ERROR]   File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
[2015-01-08 12:09:09] [Wrapper.py/ERROR]     return _iterencode(o, 0)
[2015-01-08 12:09:09] [Wrapper.py/ERROR] TypeError: keys must be a string

**Comment by benbaptist** [comment]
Oh yeah, the issue is that player.uuid is a UUID object from the uuid
module, not a regular every-day string (even though it often appears to
be). You'll need to str() it before putting it in a data object. I do need
to fix the data storage though to handle errors like that better, though I
have no clue how well it would work.

**Comment by suresttexas00** [comment]
thanks!
so 
name = str(player.uuid)

??

**Comment by benbaptist** [comment]
Yup!

**Comment by suresttexas00** [comment]
OK. Thanks!
