### ISSUE TITLE
self.<data>.Save() problem

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#56]
More information on the save issue:
After using /sethome, I can TP to that home using /home.  However, the data does not save to the disk.  The end result is that homes.json is completely blank.. not even the initial {} that is started out with before executing sethome.

WRAPPER
[2015-01-08 12:49:37] [Wrapper.py/INFO] Plugins reloaded
[2015-01-08 12:50:24] [Wrapper.py/INFO] SurestTexas00 executed: /sethome 
[2015-01-08 12:50:24] [Simple Plugin/DEBUG] sethome used '4f953255-6775-4dc6-a612-fb4230588eff' as the UUID for that command
[2015-01-08 12:50:24] [Simple Plugin/DEBUG] sethome set a home for '4f953255-6775-4dc6-a612-fb4230588eff' AKA 'SurestTexas00' at '(233.3528345205924, 64.0, -58.97286743864844)'

SERVER
[12:49:37] [Wrapper.py/INFO] Plugins reloaded
[12:50:24] [Wrapper.py/INFO] SurestTexas00 executed: /sethome
Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Wrapper\storage.py", line 39, in periodicSave
    self.save()
  File "Wrapper\storage.py", line 56, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string

Plugin code snippets:
___________________
	def onEnable(self):
		# DATA
		self.homes = self.api.getStorage("homes", True)
		self.opmail = self.api.getStorage("opmail", True)

		# DEFAULTS
		if "homes" not in self.homes: 
			self.homes["homes"] = {}
		if "opmailbox" not in self.opmail: 
			self.opmail["opmailbox"] = {}

	def onDisable(self):
		self.homes.save()
		self.opmail.save()

	def _sethome(self, player, args):
		name = player.uuid
		humanname = player.username
		self.log.debug("sethome used '%s' as the UUID for that command" % name)
		if len(args) == 0:
			player.message({"text": "Home set!", "color": "gold"})
			self.homes["homes"][name] = player.getPosition()
			self.log.debug("sethome set a home for '%s' AKA '%s' at '%s'" % (name, humanname, (self.homes["homes"][name])))
		else:
			player.message({"text": "sethome does not take any arguments!", "color": "red"})

**Comment by suresttexas00** [comment]
Closed (unless you want to keep open).  Caused by using non-string type object to write file with.
