### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#57]
I dont know what this is about. It does not seem to cause me any problems:

When the player exits:

C:\Users\JRUSSELL\Desktop\vanilla>python Wrapper\
[16:05:13] [Wrapper.py/INFO] Wrapper.py started - Version 0.7.5 (development bui
ld #70)
[16:05:13] [Wrapper.py/INFO] Loading plugins...
[16:05:13] [Wrapper.py/INFO] Loading plugin simple.py...
[16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'spawn'
[16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'sethome'
[16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'home'
[16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'simple'
[16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'ophelp'
[16:05:13] [Wrapper.py/INFO] Starting server...
[16:05:18] [Server thread/INFO]: Starting minecraft server version 1.8.1
[16:05:18] [Server thread/INFO]: Loading properties
[16:05:18] [Server thread/INFO]: Default game type: ADVENTURE
[16:05:18] [Server thread/INFO]: Generating keypair
[16:05:18] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:25565
[16:05:18] [Server thread/INFO]: Using default channel type
[16:05:18] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE
!
[16:05:18] [Server thread/WARN]: The server will make no attempt to authenticate
 usernames. Beware.
[16:05:18] [Server thread/WARN]: While this makes the game possible to play with
out internet access, it also opens up the ability for hackers to connect with an
y username they choose.
[16:05:18] [Server thread/WARN]: To change this, set "online-mode" to "true" in
the server.properties file.
[16:05:18] [Server thread/INFO]: Preparing level "AllTheWorld"
[16:05:18] [Server thread/INFO]: Preparing start region for level 0
[16:05:19] [Server thread/INFO]: Done (1.060s)! For help, type "help" or "?"
[16:05:19] [Wrapper.py/INFO] Server started
[16:06:18] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a
612-fb4230588eff | IP: 184.18.6.142)
[16:06:18] [Server thread/INFO]: SurestTexas00[/127.0.0.1:56424] logged in with
entity id 122 at (233.3528345205924, 64.0, -58.97286743864844)
[16:06:18] [Server thread/INFO]: SurestTexas00 joined the game
[16:07:07] [Wrapper.py/INFO] SurestTexas00 executed: /sethome
[16:08:26] [Wrapper.py/INFO] SurestTexas00 executed: /spawn
[16:08:26] [Server thread/INFO]: Teleported SurestTexas00 to 228.5, 65.0, -59.5
[16:08:44] [Wrapper.py/INFO] SurestTexas00 executed: /simple help
Last packet IDs (Server->Client) before disconnection:
[('0x15', 7), ('0x12', 9), ('0x16', 6), ('0x19', 4), ('0x1a', 6), ('0x17', 9), (
'0x19', 4), ('0x17', 9), ('0x19', 4), ('0x0', 6)]
Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 757, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 817, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 841, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 999, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

Last packet IDs (Server->Client) before disconnection:
[('0x15', 7), ('0x12', 9), ('0x16', 6), ('0x19', 4), ('0x1a', 6), ('0x17', 9), (
'0x19', 4), ('0x17', 9), ('0x19', 4), ('0x0', 6)]
[16:09:04] [Server thread/INFO]: SurestTexas00 lost connection: TranslatableComp
onent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOExcept
ion: An existing connection was forcibly closed by the remote host], siblings=[]
, style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=nu
ll, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[16:09:04] [Server thread/INFO]: SurestTexas00 left the game

**Comment by benbaptist** [comment]
Oh yeah, if you have debug mode enabled, an awful lot of extra junk prints
out when a user disconnects. The traceback is mostly just referring to the
fact that the socket got killed, but it's all handled and fine. I won't
need to print the extra junk out once I manage to crush the couple of bugs
that proxy mode seems to suffer.

On Thu, Jan 8, 2015 at 4:12 PM, Surest Texas <notifications@github.com>
wrote:

> I dont know what this is about. It does not seem to cause me any problems:
>
> When the player exits:
>
> C:\Users\JRUSSELL\Desktop\vanilla>python Wrapper\
> [16:05:13] [Wrapper.py/INFO] Wrapper.py started - Version 0.7.5
> (development bui
> ld #70)
> [16:05:13] [Wrapper.py/INFO] Loading plugins...
> [16:05:13] [Wrapper.py/INFO] Loading plugin simple.py...
> [16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'spawn'
> [16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'sethome'
> [16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'home'
> [16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'simple'
> [16:05:13] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'ophelp'
> [16:05:13] [Wrapper.py/INFO] Starting server...
> [16:05:18] [Server thread/INFO]: Starting minecraft server version 1.8.1
> [16:05:18] [Server thread/INFO]: Loading properties
> [16:05:18] [Server thread/INFO]: Default game type: ADVENTURE
> [16:05:18] [Server thread/INFO]: Generating keypair
> [16:05:18] [Server thread/INFO]: Starting Minecraft server on
> 127.0.0.1:25565
> [16:05:18] [Server thread/INFO]: Using default channel type
> [16:05:18] [Server thread/WARN]: **** SERVER IS RUNNING IN
> OFFLINE/INSECURE MODE
> !
> [16:05:18] [Server thread/WARN]: The server will make no attempt to
> authenticate
> usernames. Beware.
> [16:05:18] [Server thread/WARN]: While this makes the game possible to
> play with
> out internet access, it also opens up the ability for hackers to connect
> with an
> y username they choose.
> [16:05:18] [Server thread/WARN]: To change this, set "online-mode" to
> "true" in
> the server.properties file.
> [16:05:18] [Server thread/INFO]: Preparing level "AllTheWorld"
> [16:05:18] [Server thread/INFO]: Preparing start region for level 0
> [16:05:19] [Server thread/INFO]: Done (1.060s)! For help, type "help" or
> "?"
> [16:05:19] [Wrapper.py/INFO] Server started
> [16:06:18] [Wrapper.py/INFO] SurestTexas00 logged in (UUID:
> 4f953255-6775-4dc6-a
> 612-fb4230588eff | IP: 184.18.6.142)
> [16:06:18] [Server thread/INFO]: SurestTexas00[/127.0.0.1:56424] logged
> in with
> entity id 122 at (233.3528345205924, 64.0, -58.97286743864844)
> [16:06:18] [Server thread/INFO]: SurestTexas00 joined the game
> [16:07:07] [Wrapper.py/INFO] SurestTexas00 executed: /sethome
> [16:08:26] [Wrapper.py/INFO] SurestTexas00 executed: /spawn
> [16:08:26] [Server thread/INFO]: Teleported SurestTexas00 to 228.5, 65.0,
> -59.5
> [16:08:44] [Wrapper.py/INFO] SurestTexas00 executed: /simple help
> Last packet IDs (Server->Client) before disconnection:
> [('0x15', 7), ('0x12', 9), ('0x16', 6), ('0x19', 4), ('0x1a', 6), ('0x17',
> 9), (
> '0x19', 4), ('0x17', 9), ('0x19', 4), ('0x0', 6)]
> Failed to grab packet (SERVER)
> Traceback (most recent call last):
> File "Wrapper\proxy.py", line 757, in handle
> id, original = self.packet.grabPacket()
> File "Wrapper\proxy.py", line 817, in grabPacket
> dataLength = self.unpack_varInt()
> File "Wrapper\proxy.py", line 841, in unpack_varInt
> val = struct.unpack('B', self.recv(1))[0]
> File "Wrapper\proxy.py", line 999, in recv
> d = self.socket.recv(length)
> File "C:\Python27\lib\socket.py", line 170, in _dummy
> raise error(EBADF, 'Bad file descriptor')
> error: [Errno 9] Bad file descriptor
>
> Last packet IDs (Server->Client) before disconnection:
> [('0x15', 7), ('0x12', 9), ('0x16', 6), ('0x19', 4), ('0x1a', 6), ('0x17',
> 9), (
> '0x19', 4), ('0x17', 9), ('0x19', 4), ('0x0', 6)]
> [16:09:04] [Server thread/INFO]: SurestTexas00 lost connection:
> TranslatableComp
> onent{key='disconnect.genericReason', args=[Internal Exception:
> java.io.IOExcept
> ion: An existing connection was forcibly closed by the remote host],
> siblings=[]
> , style=Style{hasParent=false, color=null, bold=null, italic=null,
> underlined=nu
> ll, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
> [16:09:04] [Server thread/INFO]: SurestTexas00 left the game
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/benbaptist/minecraft-wrapper/issues/57>.
>



-- 
http://sawmaster2.no-ip.org:82/

iPod network
