### ISSUE TITLE
 self.proxy.getClientByServerUUID(data["uuid"]).uuid,

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#59]
Is something that needs attention?

[2015-01-11 13:31:04] [Simple Plugin/DEBUG] home used '573119bd-92d0-4b31-935f-bbc9581c14ad' as the UUID for that command
[2015-01-11 13:31:04] [Simple Plugin/DEBUG] home TP'd '573119bd-92d0-4b31-935f-bbc9581c14ad' AKA 'JRCool2003' to '[1880.8042008759726, 63.0, 1790.8078141715862]'
[2015-01-11 13:31:51] [Wrapper.py/INFO] JRCool2003 executed: /home 
[2015-01-11 13:31:51] [Simple Plugin/DEBUG] home used '573119bd-92d0-4b31-935f-bbc9581c14ad' as the UUID for that command
[2015-01-11 13:31:51] [Simple Plugin/DEBUG] home TP'd '573119bd-92d0-4b31-935f-bbc9581c14ad' AKA 'JRCool2003' to '[1880.8042008759726, 63.0, 1790.8078141715862]'
[2015-01-11 13:38:01] [Wrapper.py/INFO] Aiko_Crimson logged in (UUID: 21305e70-6c58-46ae-b20c-100b143bc015 | IP: 67.10.194.27)
[2015-01-11 13:38:13] [Wrapper.py/INFO] Aiko_Crimson logged in (UUID: 21305e70-6c58-46ae-b20c-100b143bc015 | IP: 67.10.194.27)
[2015-01-11 13:39:15] [Wrapper.py/DEBUG] Could not parse packet, connection may crumble:
[2015-01-11 13:39:15] [Wrapper.py/DEBUG] Traceback (most recent call last):
[2015-01-11 13:39:15] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 777, in handle
[2015-01-11 13:39:15] [Wrapper.py/DEBUG]     if self.parse(id, original) and self.safe:
[2015-01-11 13:39:15] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 629, in parse
[2015-01-11 13:39:15] [Wrapper.py/DEBUG]     self.proxy.getClientByServerUUID(data["uuid"]).uuid,
[2015-01-11 13:39:15] [Wrapper.py/DEBUG] AttributeError: 'UUID' object has no attribute 'uuid'
[2015-01-11 13:39:15] [Wrapper.py/DEBUG] 
[2015-01-11 13:40:30] [Wrapper.py/DEBUG] Could not parse packet, connection may crumble:
[2015-01-11 13:40:30] [Wrapper.py/DEBUG] Traceback (most recent call last):
[2015-01-11 13:40:30] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 777, in handle
[2015-01-11 13:40:30] [Wrapper.py/DEBUG]     if self.parse(id, original) and self.safe:
[2015-01-11 13:40:30] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 629, in parse
[2015-01-11 13:40:30] [Wrapper.py/DEBUG]     self.proxy.getClientByServerUUID(data["uuid"]).uuid,
[2015-01-11 13:40:30] [Wrapper.py/DEBUG] AttributeError: 'UUID' object has no attribute 'uuid'
[2015-01-11 13:40:30] [Wrapper.py/DEBUG] 
[2015-01-11 13:40:39] [Wrapper.py/DEBUG] Could not parse packet, connection may crumble:
[2015-01-11 13:40:39] [Wrapper.py/DEBUG] Traceback (most recent call last):
[2015-01-11 13:40:39] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 777, in handle
[2015-01-11 13:40:39] [Wrapper.py/DEBUG]     if self.parse(id, original) and self.safe:
[2015-01-11 13:40:39] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 629, in parse
[2015-01-11 13:40:39] [Wrapper.py/DEBUG]     self.proxy.getClientByServerUUID(data["uuid"]).uuid,
[2015-01-11 13:40:39] [Wrapper.py/DEBUG] AttributeError: 'UUID' object has no attribute 'uuid'
[2015-01-11 13:40:39] [Wrapper.py/DEBUG] 
[2015-01-11 13:41:44] [Wrapper.py/INFO] xXRhianna_ZoltXx executed: /home 
[2015-01-11 13:41:44] [Simple Plugin/DEBUG] home used '97b5d3bd-0bf1-4090-9eda-ab30e5d7ba2a' as the UUID for that command
[2015-01-11 13:41:44] [Simple Plugin/DEBUG] home TP'd '97b5d3bd-0bf1-4090-9eda-ab30e5d7ba2a' AKA 'xXRhianna_ZoltXx' to '[-10772.493511905845, 72.0, 1546.700800083902]'
[2015-01-11 13:41:45] [Wrapper.py/DEBUG] Could not parse packet, connection may crumble:
[2015-01-11 13:41:45] [Wrapper.py/DEBUG] Traceback (most recent call last):
[2015-01-11 13:41:45] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 777, in handle
[2015-01-11 13:41:45] [Wrapper.py/DEBUG]     if self.parse(id, original) and self.safe:
[2015-01-11 13:41:45] [Wrapper.py/DEBUG]   File "Wrapper\proxy.py", line 629, in parse
[2015-01-11 13:41:45] [Wrapper.py/DEBUG]     self.proxy.getClientByServerUUID(data["uuid"]).uuid,
[2015-01-11 13:41:45] [Wrapper.py/DEBUG] AttributeError: 'UUID' object has no attribute 'uuid'
[2015-01-11 13:41:45] [Wrapper.py/DEBUG] 
[2015-01-11 13:44:38] [Wrapper.py/INFO] Aiko_Crimson logged in (UUID: 21305e70-6c58-46ae-b20c-100b143bc015 | IP: 67.10.194.27)
[2015-01-11 13:44:49] [Wrapper.py/INFO] JRCool2003 executed: /home 
[2015-01-11 13:44:49] [Simple Plugin/DEBUG] home used '573119bd-92d0-4b31-935f-bbc9581c14ad' as the UUID for that command
[2015-01-11 13:44:49] [Simple Plugin/DEBUG] home TP'd '573119bd-92d0-4b31-935f-bbc9581c14ad' AKA 'JRCool2003' to '[1880.8042008759726, 63.0, 1790.8078141715862]'
[2015-01-11 13:46:15] [Wrapper.py/INFO] Aiko_Crimson executed: /home

**Comment by benbaptist** [comment]
Are other players not able to see each other when this happens/at all? If so, then that's what this means. If players can still see each other though, then I'm not sure why this error is spewing out and not causing other issues.

**Comment by suresttexas00** [comment]
not really sure.. I think I may have noticed instances of people disappearing...

**Comment by suresttexas00** [comment]
I think i have overheard chats about people being invisible...

**Comment by Aiko-Crimson** [comment]
So wait, what is going on?
