### ISSUE TITLE
test is another player is OP

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#61]
Are there any methods that test whether a another player is op (besides the player instance)?

For instance, I get the list of online players and see if any are Ops:

	def _someCmd(self, player, args):
		players = self.minecraft.getPlayers()
		text = (" ")
		text = text.join(players)
		listplayers = text.split()
		for indexops in range(len(listplayers)):
			if listplayers[indexops].isOp(): <==== obviously that is not valid :)
				#do something

In case you are wondering why I would want to do such as think in the player instance, this is in the context of a social spy function so that ops are privy to /tell  commands in order to monitor for malicious whisperings.  my own /tell is registered  and behaves identically to the vanilla command, but sends tellraw messages to the ops currently logged on with the whisper contents.

**Comment by benbaptist** [comment]
If I'm not mistaken, I think a cleaner way would just be to do this:

for name in self.minecraft.getPlayers():
    if self.minecraft.getPlayer(name).isOp():
        print name + " is operator"

Also, to get the player object from just a name, as you can see in the example, I use minecraft.getPlayer(name). I'm not sure if this is what you wanted, though.

**Comment by suresttexas00** [comment]
no, that is perfect.. another example for me to understand how this object-oriented stuff works.  Most of my programming experience was "back in the day" stuff with basic, with numbered code lines, goto, for-next, if-then, etc, and.. bascially what are now just scripts... the closest thing to this is I have done for VB for applications a few years ago with Microsoft Access/Word/Excel...

**Comment by suresttexas00** [comment]
Now what am i doing wrong?

This code WORKS:

		#Error checking for valid otherplayer
		players = self.minecraft.getPlayers()
		playeron = False
		text = (" ")
		text = text.join(players)
		listplayers = text.split()
		for indexpl in range(len(listplayers)):
			if listplayers[indexpl] == otherplayer:
				playeron = True

This DOES NOT:

		for targetname in self.minecraft.getPlayers():
			if self.minecraft.getPlayer(targetname) == otherplayer:
				playeron = True

(otherplayer = args[0], earlier in code)

**Comment by suresttexas00** [comment]
Here is the output from the second code snippet:
[2015-01-11 20:24:17] [Wrapper.py/INFO] Minecraftboy2019 executed: /tell SurestTexas00 hello there d00d
[2015-01-11 20:24:17] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.simple' errored out when executing command: '<Minecraftboy2019> /{'callback': <bound method Main._tell of <simple.Main instance at 0x02CB8FA8>>, 'permission': None}':
[2015-01-11 20:24:17] [Wrapper.py/ERROR] Traceback (most recent call last):
[2015-01-11 20:24:17] [Wrapper.py/ERROR]   File "C:\Users\JRUSSELL\Desktop\vanilla\Wrapper\__main__.py", line 374, in playerCommand
[2015-01-11 20:24:17] [Wrapper.py/ERROR]     command["callback"](payload["player"], payload["args"])
[2015-01-11 20:24:17] [Wrapper.py/ERROR]   File "wrapper-plugins\simple.py", line 237, in _tell
[2015-01-11 20:24:17] [Wrapper.py/ERROR]     if self.minecraft.getPlayer(targetname) == otherplayer:
[2015-01-11 20:24:17] [Wrapper.py/ERROR]   File "Wrapper\api\minecraft.py", line 64, in getPlayer
[2015-01-11 20:24:17] [Wrapper.py/ERROR]     raise Exception("No such player %s is logged in" % name)
[2015-01-11 20:24:17] [Wrapper.py/ERROR] NameError: global name 'name' is not defined
[2015-01-11 20:24:17] [Wrapper.py/ERROR] 
[2015-01-11 20:24:29] [Wrapper.py/INFO] SurestTexas00 executed: /tell Minecraftboy2019 hello
[2015-01-11 20:24:29] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.simple' errored out when executing command: '<SurestTexas00> /{'callback': <bound method Main._tell of <simple.Main instance at 0x02CB8FA8>>, 'permission': None}':
[2015-01-11 20:24:29] [Wrapper.py/ERROR] Traceback (most recent call last):
[2015-01-11 20:24:29] [Wrapper.py/ERROR]   File "C:\Users\JRUSSELL\Desktop\vanilla\Wrapper\__main__.py", line 374, in playerCommand
[2015-01-11 20:24:29] [Wrapper.py/ERROR]     command["callback"](payload["player"], payload["args"])
[2015-01-11 20:24:29] [Wrapper.py/ERROR]   File "wrapper-plugins\simple.py", line 237, in _tell
[2015-01-11 20:24:29] [Wrapper.py/ERROR]     if self.minecraft.getPlayer(targetname) == otherplayer:
[2015-01-11 20:24:29] [Wrapper.py/ERROR]   File "Wrapper\api\minecraft.py", line 64, in getPlayer
[2015-01-11 20:24:29] [Wrapper.py/ERROR]     raise Exception("No such player %s is logged in" % name)
[2015-01-11 20:24:29] [Wrapper.py/ERROR] NameError: global name 'name' is not defined
[2015-01-11 20:24:29] [Wrapper.py/ERROR]

**Comment by benbaptist** [comment]
Oh crud. Your code is perfect - but I made a mistake in the getPlayer
method. It actually has been bugged for quite some time, and I even just
realized this while implementing /help. I'll push the latest code to fix
that.
