### ISSUE TITLE
Error while players connect

### ISSUE THREAD

**Issue by kirr9999** [benbaptist/minecraft-wrapper#617]
While some player connects, I'm getting this error in console. I use SpongeForge Server 1.12.2 and the latest stable build of wrapper.
`[2018-07-21 09:05:28] [Wrapper.py/ERROR]: [31;40;1m'NoneType' object has no attribute 'string'[0m
Traceback (most recent call last):
  File "Wrapper.py/core/mcserver.py", line 216, in handle_server
    self.readconsole(line.replace("\r", ""))
  File "Wrapper.py/core/mcserver.py", line 934, in readconsole
    self.login(name, eid, location, ip_addr)
  File "Wrapper.py/core/mcserver.py", line 398, in login
    self.vitals.players[username] = Player(username, self.wrapper)
  File "Wrapper.py/api/player.py", line 247, in __init__
    self.mojangUuid.string, root="wrapper-data/players")
AttributeError: 'NoneType' object has no attribute 'string'`

**Comment by suresttexas00** [comment]
I have been away for a couple weeks. so sorry for a late reply.  the error is caused by a non standard output from the Spongeforge server.   To diagnose this, I need the full __server__ output that caused the error.  I need a cut and paste of the actual server lines where the player logged in.

I assume you are _not_ running in proxy mode, correct?

**Comment by RyoshiKayo** [comment]
Having the same issue with SpongeForge, not running as a proxy. I can try and take a look as well, although I'm fairly new to this project and code base.

```
[01:29:55] [User Authenticator #4/INFO] [minecraft/NetHandlerLoginServer]: UUID of player <user> is <UUID>
[01:29:55] [Netty Epoll Server IO #9/INFO] [FML]: Client protocol version 2
[01:29:55] [Netty Epoll Server IO #9/INFO] [FML]: Client attempting to join with 50 mods : <snip>
[01:29:55] [Netty Epoll Server IO #9/INFO] [journeymap]: CLIENT
[01:29:55] [Netty Epoll Server IO #9/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, spongeforge, discordbridge, eaglefactions, jmfixer, luckperms, prism] at CLIENT
[01:29:56] [Netty Epoll Server IO #9/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
[01:30:01] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[01:30:01] [Server thread/INFO] [journeymap]: <user> joining dimension 0
[01:30:01] [Server thread/INFO] [minecraft/PlayerList]: <user>[/<ip>:<port>] logged in with entity id 1167871 in world(0) at (-2889.226250471687, 91.0, -45.9445773368453)
[01:30:01] [Wrapper.py/WARNING]: UUID returned False (a non-MCUUID object).  This will likely create other logical/program flow errors
[01:30:01] [Wrapper.py/ERROR]: 'bool' object has no attribute 'string'
Traceback (most recent call last):
  File "Wrapper.py/core/mcserver.py", line 233, in handle_server
    self.readconsole(line.replace("\r", ""))
  File "Wrapper.py/core/mcserver.py", line 945, in readconsole
    self.login(name, eid, location, ip_addr)
  File "Wrapper.py/core/mcserver.py", line 415, in login
    self.wrapper.players[username] = Player(username, self.wrapper)
  File "Wrapper.py/api/player.py", line 247, in __init__
    self.mojangUuid.string, root="wrapper-data/players")
AttributeError: 'bool' object has no attribute 'string'
```

**Comment by suresttexas00** [comment]
Wrapper is not presently well designed for Forge varieties because Forge uses a modified minecraft protocol.  If you search all the issues for "Forge" under this issues page (including closed ones), you will get a better idea of the issues involved.

**Comment by suresttexas00** [comment]
https://github.com/benbaptist/minecraft-wrapper/issues?utf8=%E2%9C%93&q=Forge+in%3Atitle%2Cbody
