### ISSUE TITLE
Player execute causes disconnection

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#62]
self.api.registerCommand("minecraft:help", self._mchelp)

	def _mchelp(self, player, args):
		if len(args) == 0:   #just plain old Minecraft help
			player.execute("help")
		if len(args) == 1:   #just plain old Minecraft help page <>
			player.execute("help %s" % (args[0]))
		if len(args) > 1:
			player.message("&cToo many arguments!  Just need a page number!" % helptext)

C:\Users\JRUSSELL\Desktop\vanilla>python Wrapper\
[21:44:44] [Wrapper.py/INFO] Wrapper.py started - Version 0.7.5 (development bui
ld #71)
[21:44:44] [Wrapper.py/INFO] Loading plugins...
[21:44:44] [Wrapper.py/INFO] Loading plugin simple.py...
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered event 'player.login'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered event 'player.logout'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'help'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'minecraft:help
'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'tell'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'msg'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'whisper'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'wh'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'w'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'spawn'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'sethome'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'sethm'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'seth'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'sh'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'h'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'hm'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'home'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'simple'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 's'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'helpop'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'ophelp'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'op'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'opbox'
[21:44:44] [Wrapper.py/DEBUG] [Simple Plugin] Registered command 'cube'
[21:44:44] [Wrapper.py/INFO] Starting server...
[21:44:49] [Server thread/INFO]: Starting minecraft server version 1.8.2-pre1
[21:44:49] [Server thread/INFO]: Loading properties
[21:44:49] [Server thread/INFO]: Default game type: ADVENTURE
[21:44:49] [Server thread/INFO]: Generating keypair
[21:44:49] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:25565
[21:44:49] [Server thread/INFO]: Using default channel type
[21:44:49] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE
!
[21:44:49] [Server thread/WARN]: The server will make no attempt to authenticate
 usernames. Beware.
[21:44:49] [Server thread/WARN]: While this makes the game possible to play with
out internet access, it also opens up the ability for hackers to connect with an
y username they choose.
[21:44:49] [Server thread/WARN]: To change this, set "online-mode" to "true" in
the server.properties file.
[21:44:49] [Server thread/INFO]: Preparing level "AllTheWorld"
[21:44:49] [Server thread/INFO]: Preparing start region for level 0
[21:44:50] [Server thread/INFO]: Preparing spawn area: 80%
[21:44:50] [Server thread/INFO]: Done (1.271s)! For help, type "help" or "?"
[21:44:50] [Wrapper.py/INFO] Server started
[21:44:57] [Wrapper.py/INFO] Minecraftboy2019 logged in (UUID: 54880482-2b03-47e
5-a268-8290fd1e0b46 | IP: 184.18.6.142)
[21:44:57] [Server thread/INFO]: Minecraftboy2019[/127.0.0.1:54038] logged in wi
th entity id 69 at (-3.438708432677755, 67.5, 55.10378548377859)
[21:44:57] [Server thread/INFO]: Minecraftboy2019 joined the game
[21:45:02] [Wrapper.py/INFO] Minecraftboy2019 executed: /minecraft:help
Last packet IDs (Server->Client) before disconnection:
[('0x16', 5), ('0x19', 3), ('0x15', 7), ('0x15', 7), ('0x12', 9), ('0x18', 18),
('0x19', 4), ('0x19', 4), ('0x19', 4), ('0x15', 7)]
Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 759, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper\proxy.py", line 819, in grabPacket
    dataLength = self.unpack_varInt()
  File "Wrapper\proxy.py", line 843, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "Wrapper\proxy.py", line 1001, in recv
    d = self.socket.recv(length)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

Last packet IDs (Server->Client) before disconnection:
[('0x16', 5), ('0x19', 3), ('0x15', 7), ('0x15', 7), ('0x12', 9), ('0x18', 18),
('0x19', 4), ('0x19', 4), ('0x19', 4), ('0x15', 7)]
[21:45:02] [Server thread/INFO]: Minecraftboy2019 lost connection: TranslatableC
omponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOExc
eption: An existing connection was forcibly closed by the remote host], siblings
=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined
=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[21:45:02] [Server thread/INFO]: Minecraftboy2019 left the game

**Comment by suresttexas00** [comment]
I think this was caused by a corrupted instance of wrapper.
