### ISSUE TITLE
Supported version

### ISSUE THREAD

**Issue by BololZ** [benbaptist/minecraft-wrapper#621]
Hello,

Does the minecraft-wrapper support Minecraft 1.13.1 with protocol 401 ?
Because i have problem and the console sys Exception in thread Thread-20:

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "Wrapper.py/proxy/server/serverconnection.py", line 148, in handle
>     if self.parse(pkid) and self.client.state == PLAY:
>   File "Wrapper.py/proxy/server/serverconnection.py", line 283, in parse
>     return self.parsers[self.state][pkid]()
>   File "Wrapper.py/proxy/server/parse_cb.py", line 407, in play_time_update
>     data = self.packet.readpkt([LONG, LONG])
>   File "Wrapper.py/proxy/packets/packet.py", line 336, in readpkt
>     item = self._PKTREAD[arg]()
>   File "Wrapper.py/proxy/packets/packet.py", line 676, in read_long
>     return struct.unpack(">q", self.read_data(8))[0]
> struct.error: unpack requires a bytes object of length 8

Thank for your excellent project.

**Comment by suresttexas00** [comment]
No,

I have not had time to compare and update all the protocol parsing.
