### ISSUE TITLE
New help function error

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#78]
Here is the error:
```
[23:48:41] [Wrapper.py/INFO] Loading plugin social.py...
[23:48:41] [Wrapper.py/DEBUG] [Social Plugin] Registered help group 'Social' wit
h 2 commands
[23:48:47] [Wrapper.py/INFO] Minecraftboy2019 executed: /help
[23:49:19] [Wrapper.py/INFO] Minecraftboy2019 executed: /help social
[23:50:11] [Wrapper.py/INFO] Minecraftboy2019 executed: /helpop message to op
[23:50:11] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.social' errored
out when executing command: '<Minecraftboy2019> /{'callback': <bound method Main
._ophelp of <social.Main instance at 0x02D04A80>>, 'permission': True}':
[23:50:11] [Wrapper.py/ERROR] Traceback (most recent call last):
[23:50:11] [Wrapper.py/ERROR]   File "C:\Users\JRUSSELL\Desktop\vanilla\Wrapper\
__main__.py", line 173, in playerCommand
[23:50:11] [Wrapper.py/ERROR]     if player.hasPermission(command["permission"])
:
[23:50:11] [Wrapper.py/ERROR]   File "Wrapper\api\player.py", line 121, in hasPe
rmission
[23:50:11] [Wrapper.py/ERROR]     if uuid in self.permissions["users"]:
[23:50:11] [Wrapper.py/ERROR]   File "Wrapper\storage.py", line 22, in __getitem
__
[23:50:11] [Wrapper.py/ERROR]     return self.data[index]
[23:50:11] [Wrapper.py/ERROR] KeyError: 'users'
[23:50:11] [Wrapper.py/ERROR]
```

Here is how I registered everything... I was note sure if the permission nodes were a required argument, so I handled them simliar to command registering by using True for default commands:

```
		self.api.registerHelp("Social","Basic social messaging commands like /helpop, /mail, etc", 
						[
							("/helpop <message>", "Sends the <message> to the general Op mailbox.", True),
							("/whisper <username> <message>", "Same as Minecraft /tell or /msg - private chat", True)
							#("/mail", "Not implemented yet!", "social.user")
						]
						)
```

The command that errored out:
```
	def _ophelp(self, player, args):
		name = player.username
		if len(args) == 1:
			subcommand = args[0]
			if subcommand == "check":
				if name not in self.opmail["opmailbox"]:
					player.message("&eYou have no mail for the OP to read.")
					return
				else:
					if len(self.opmail["opmailbox"][name]) == 0:
						player.message("&eYou have no mail for the OP to read.")
						return
					else:
						messages = self.opmail["opmailbox"][name]
						player.message("&bYour Messages: ")
						player.message("&3 %s -\n %s" % (name, messages))
						return
			else:
				player.message({"text": "Nothing sent! - message too short or subcommand not recognized", "color": "red"})
				return
		if len(args) > 0:
			text = (" ")
			text = text.join(args)
			text = text.replace("\"","'")
			text = "MESSAGE:: "+ (text) + ("  ")
			if name not in self.opmail["opmailbox"]:
				self.opmail["opmailbox"][name] = text
				player.message("&eMessage delivered to general OP mailbox.")
			else:
				mailbox = text + "\n " + self.opmail["opmailbox"][name] 
				self.opmail["opmailbox"][name] = mailbox
				player.message("&eMessage delivered, but you still have existing messages that have not been read by an OP.")
		else:
			player.message({"text": "Nothing sent!", "color": "red"})
			player.message({"text": "usage: helpop <message>/check -  Send a <message> (more\n  than a word) to the OP's mailbox or 'check' to see\n  messages you sent already", "color": "red"})
```

**Comment by suresttexas00** [comment]
seems it must not have liked True for the permissions.  I used "" instead and it seems to have worked as intended.  
ONE thing..  I think the gold is too overpowering in the ##bold##
