### ISSUE TITLE
Help errors

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#90]
The error-
```
23:42:07] [Wrapper.py/INFO] Minecraftboy2019 executed: /help Social
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 329, in parse
    return self.wrapper.callEvent("player.runCommand", {"player": self.getPlayer
Object(), "command": args(0)[1:], "args": argsAfter(1)})
  File "C:\Users\JRUSSELL\Desktop\vanilla\Wrapper\__main__.py", line 133, in cal
lEvent
    if not self.playerCommand(payload): return False
  File "C:\Users\JRUSSELL\Desktop\vanilla\Wrapper\__main__.py", line 321, in pla
yerCommand
    if not player.hasPermission(i[2]):
  File "Wrapper\api\player.py", line 121, in hasPermission
    if uuid in self.permissions["users"]:
  File "Wrapper\storage.py", line 22, in __getitem__
    return self.data[index]
KeyError: 'users'
```

The plugin help code:
```
		# REGISTER HELP
		self.api.registerHelp("Social","Basic social messaging commands like /helpop, /mail, etc", 
						[
							("/helpop <message>", "Sends the <message> (more than one word) to the general Op mailbox. ", "player"),
							("/helpop check", "View messages you have waiting in the Op mailbox.", "player"),
							("/whisper <username> <message>", "alias for /tell or /msg (private chat)", "player"),
							#("/msg <username> <message>", "duh!", "player"),
							("/opbox <read> [delete]", "Read the general Op mailbox [delete] additionally deletes Op mailbox", "OP"),
							("/mail", "Not implemented yet!", "player")
							#("/")
						]
						)
```

**Comment by suresttexas00** [comment]
fixed in last release
